// Danish → English glossary used by the hover translator (js/translate.js).
// One entry per line: word=translation. Keys are lowercase word forms exactly
// as they appear in the app. Add a line here when you add new content.
PD2.GLOSSARY_RAW = `
a-h=A to H
aarhus=Aarhus (city)
acceptabel=acceptable
adgang=access
adjektiv=adjective
adressen=the address
af=of / by / from
afbud=cancellation (saying you can't come)
afhængig=dependent
afhængighedsskabende=addictive
aflevere=to hand in / to deliver
aflyse=to cancel
afskedsfest=farewell party
afslut=finish
afslutning=ending / conclusion
afslutter=finish / end
afsluttes=is finished / ends
afslører=reveals
afsnit=paragraph / section
afspænding=relaxation
aftale=appointment / agreement
aftaler=agree / arrange
aftenen=the evening
aftenkaffen=the evening coffee
aftenskole=evening school
aftensmad=dinner
agurker=cucumbers
al=all
aldrig=never
alene=alone
alle=all / everyone
alligevel=anyway / still
allé=avenue
alsidig=all-round / versatile
alt=everything / all
altan=balcony
altid=always
alvorlig=serious
anbefale=to recommend
anbefaler=recommend(s)
anden=other / second
andet=other / else
andre=others / other
angående=regarding
annonce=advertisement
annoncen=the advertisement
ansat=employed / an employee
ansatte=employees
ansøge=to apply
ansøgning=application
antallet=the number
app=app
appen=the app
arbejde=work / to work
arbejdede=worked
arbejder=works / is working
arbejdes=is worked
arbejdet=the work
arbejdsopgaver=work tasks
arbejdspladser=workplaces
arbejdspladserne=the workplaces
arbejdstider=working hours
arrangementer=events
arsenalet=the arsenal / the range
at=to / that
attraktiv=attractive
avis=newspaper
avisartikel=newspaper article
baby=baby
bad=bath / shower
badekar=bathtub
baderum=bathroom / washroom
badestrand=bathing beach
badeværelse=bathroom
badeværelser=bathrooms
badge=badge
badges=badges
bag=behind
bagefter=afterwards
bager=baker / bakery
bageri=bakery
bagerier=bakeries
bageriet=the bakery
bagud=behind
baguettes=baguettes
balance=balance
balanceøvelser=balance exercises
baller=buttocks
bange=afraid
bare=just / only
barnevogn=pram / baby carriage
baseret=based
beboere=residents
beboerne=the residents
bedre=better
bedst=best
bedste=best
bedt=asked
bedøm=assess / grade
bedømmer=assessor / grader
bedømmerarket=the assessment sheet
begge=both
begrund=give reasons for
begynder=begins / beginner
begyndere=beginners
begyndte=began
beklage=to apologise / to regret
beklager=apologise / regret
beliggende=located
beliggenheden=the location
beregn=calculate
beskriv=describe
beskrive=to describe
beslutter=decide(s)
besluttet=decided
bestemme=to decide
bestil=book / order
bestille=to book / to order
bestilte=ordered
består=consists
besøg=visit
besøge=to visit
besøger=visit(s)
besøgt=visited
betale=to pay
betragter=look at / watch
betyder=means
bevæge=to move
bevægelighed=mobility
bevægeligheden=the mobility
bevægelser=movements
bibliotek=library
biblioteket=the library
bil=car
bilen=the car
biler=cars
bilister=motorists
billig=cheap
billigere=cheaper
bindeord=connecting words / conjunctions
biografer=cinemas
bl=among others (bl.a.)
blad=magazine / leaf
bland-selv-koncept=pick-and-mix concept
bland-selv-slik=pick-and-mix sweets
blande=to mix
blander=mix(es)
blandt=among
blev=became / was
blevet=become / been
bliv=stay / become
blive=to become / to stay
bliver=becomes / is
blok=block
blot=just / only
bløde=soft
bo=to live
boblernes=the bubbles'
boede=lived
bogstav=letter (of the alphabet)
bogstav-svar=letter answer
bogstaver=letters
bogstavet=the letter
bolde=balls
bolig=home / housing
boligen=the home
boliger=homes
boligforening=housing association
boligforeningen=the housing association
boller=bread rolls
bollerne=the bread rolls
bor=live(s)
bordet=the table
borgmester=mayor
bosætter=settle
brev=letter
brombærsnitterne=the blackberry slices
brug=use / need
bruge=to use
bruger=use(s) / spend(s)
brugt=used / second-hand
brugte=used
bruseniche=shower cubicle
bruser=shower
bryggers=utility room
brænder=burn(s)
brød=bread
brødet=the bread
bus=bus
busforbindelser=bus connections
busserne=the buses
butik=shop
butikken=the shop
butikkens=the shop's
butiksmedarbejder=shop assistant
by=town / city
byde=to offer
byder=offers
byen=the town
byens=the town's
bygade=village street
bygget=built
bygning=building
både=both
bøjning=inflection
børn=children
børneafdeling=children's section
børnehave=kindergarten
børnehaven=the kindergarten
børnene=the children
børnevenligt=child-friendly
børneværelser=children's rooms
ca=approximately
cafeer=cafés
carport=carport
censor=external examiner
centralt=centrally
centrum=city centre
champagner=champagnes
charme=charm
charmerende=charming
chauffør=driver
chokoladeskærekagen=the chocolate cake
cirka=approximately
combo=combo
combo-bonus=combo bonus
computer=computer
computeren=the computer
coronapandemien=the corona pandemic
cpr-nummer=civil registration number
cykel=bicycle
cykelstier=bicycle paths
cykle=to cycle
cyklen=the bicycle
cyklende=cycling
cykler=cycle(s) / bicycles
da=when / since / then
dag=day
dage=days
dagen=the day
dagene=the days
dagens=today's / the day's
dagstur=day trip
danmark=Denmark
danmarks=Denmark's
danse=to dance
danseaerobic=dance aerobics
dansemotion=dance exercise
dansetrin=dance steps
dansk=Danish
danske=Danish
danskekspert=Danish expert
danskere=Danes
danskerne=the Danes
datingside=dating site
datingsiden=the dating site
dato=date
datoen=the date
datter=daughter
de=they / the
debatindlæg=opinion piece
december=December
dejlig=lovely
dejlige=lovely
dejligt=lovely
del=part
dele=parts / to share
deler=shares
deli=deli
delprøve=sub-test / exam part
deltage=to take part
deltager=take(s) part / participant
delvis=partly
delvist=partly
dem=them
den=it / the / that
denne=this
der=there / who / that
derefter=after that
deres=their
derfor=therefore
derhen=there (to that place)
derhjemme=at home
derimod=on the other hand / however
dertil=in addition
derudover=in addition
desuden=furthermore
desværre=unfortunately
det=it / the / that
dette=this
dialog=dialogue
dig=you
din=your
dine=your
direkte=direct(ly)
disken=the counter
diskursiv=discursive (how the text hangs together)
disponible=available / spare
dit=your
dk=.dk (Danish web address)
dobbelt=double
dog=however
drejer=is about (det drejer sig om = it's about)
drikker=drink(s)
dronningens=the queen's
drømmejob=dream job
drømmer=dream(s)
drømmested=dream place
du=you
durumbrød=durum bread
dybdeafspænding=deep relaxation
dyre=expensive
dyrere=more expensive
dyrkede=grew (plants)
dyrker=do / play (a sport)
dyrt=expensive
dørene=the doors
døtre=daughters
eddike=vinegar
efter=after
eftermiddag=afternoon
eftermiddagen=the afternoon
eftertragtet=sought-after
egen=own
eget=own
egne=own
ejendommen=the property
eksaminator=examiner
eksempel=example
eksempler=examples
eksemplet=the example
eksperter=experts
eksperterne=the experts
ekstra=extra
elastikker=elastic bands
elegant=elegant
elektriker=electrician
eleverne=the pupils
eller=or
ellers=otherwise
elsker=love(s)
emne=topic
emnet=the topic
en=a / an / one
end=than
ende=end
endelig=finally
endnu=yet / still
engelsk=English
enig=agree(d)
enige=agreed
enkelte=individual
enkeltes=the individual's
ens=one's / same
ensom=lonely
entreen=the hallway
entré=entrance hall
er=is / are
erfaring=experience
erfaringer=experiences
erne=(the …s, as in 1950'erne = the 1950s)
et=a / an / one
etplansvilla=single-storey house
europa=Europe
europæiske=European
fabrikker=factories
faciliteter=facilities
faktisk=actually
faktuelle=factual
familie=family
familien=the family
familier=families
familiestørrelse=family size
fantastisk=fantastic
fast=permanent / fixed
faste=fixed
fastfood=fast food
februar=February
feedback=feedback
fejlene=the mistakes
fejlfri=flawless
fejre=to celebrate
fejrer=celebrate(s)
fem=five
ferie=holiday
fest=party
festen=the party
fester=parties
festlokale=party room
filial=branch
find=find
finde=to find
finder=find(s)
fin=fine / nice
fine=fine / nice
fint=fine
fire=four
firma=company
firmaet=the company
fitnessrum=fitness room
fjerne=to remove
flere=more / several
flertal=plural
fleste=most
flisebelagt=tiled / paved
fliseterrasse=paved patio
flot=nice / impressive
flotte=nice / impressive
flytte=to move
flytter=move(s)
flyttet=moved
flæng=(i flæng = at random)
fokus=focus
for=for / because / too
forbedre=to improve
forbered=prepare
forberede=to prepare
forberedelse=preparation
forbindelse=connection
fordel=advantage
fordele=advantages
fordelene=the advantages
fordi=because
forebygge=to prevent
forelskede=in love
forelsket=in love
foreslå=to suggest
foreslår=suggest(s)
forhånd=(på forhånd = in advance)
forkert=wrong / false
forklar=explain
formål=purpose
forny=to renew
forside=front page
forsiden=the front page
forskellen=the difference
forskellige=different
forstå=to understand
forsøg=attempt
fortiden=the past
fortrinligt=excellent
fortræffelige=excellent
fortsætte=to continue
fortæl=tell
fortælle=to tell
fortællende=narrative
fortæller=tell(s)
foruden=besides
forventes=is expected
foråret=the spring
forårsløg=spring onions
forældre=parents
forældrene=the parents
forældresoveværelse=master bedroom
foto=photo
fotos=photos
fra=from
fransk=French
franske=French
fred=peace
fredag=Friday
fredelige=peaceful
fredeligt=peaceful
frem=forward / ahead
fremgang=progress
fremmest=(først og fremmest = first and foremost)
fremskridt=progress
fremstilling=composition / writing
fremstår=appears
fremtiden=the future
fri=free / off work
frihed=freedom
frikadeller=Danish meatballs
frisk=fresh
friskbagte=freshly baked
frisklavede=freshly made
frit=freely
fritid=free time
frivillige=volunteers
frokost=lunch
frokostpausen=the lunch break
fulgt=followed
fundet=found
fx=for example (e.g.)
fyldte=filled / turned (age)
fyr=guy
fyrværkeri=fireworks
fysioterapeut=physiotherapist
få=get / few
fået=got / received
får=get(s)
fås=is available
fælles=common / shared
fællesspisning=communal dining
færdig=finished
færdighed=skill
fødselsdag=birthday
fødselsdage=birthdays
føle=to feel
følelse=feeling
følg=follow
følge=to follow
før=before
føre=to lead / to carry on
først=first
første=first
førstegangskøbere=first-time buyers
førstesal=first floor (upstairs)
førstesalen=the first floor
gade=street
gammel=old
gang=time / walk / hallway
gange=times
gangen=the hallway
gardiner=curtains
gav=gave
gave=gift
gemt=saved
gengæld=(til gengæld = on the other hand)
gennem=through
gennemarbejder=works through
genoptræne=to rehabilitate
genskabt=recreated
gerne=gladly / would like to
gift=married
giftes=get married
gik=went
give=to give
giver=gives
gives=is given
glad=happy
glade=happy
gladere=happier
gluten=gluten
glutenfrie=gluten-free
glutenfrit=gluten-free
god=good
gode=good
godt=good / well
gourmetbagere=gourmet bakers
gratis=free (of charge)
grillbarer=snack bars
groft=rough
grund=plot of land / reason
grundig=thorough
grundige=thorough
grundlæggende=basic
græsplæne=lawn
gule=yellow
gulerodskagen=the carrot cake
gulvvarme=underfloor heating
gå=to walk / to go
gåafstand=walking distance
gået=gone / walked
går=go(es) / walk(s)
gælder=applies
gæstebadeværelse=guest bathroom
gæstetoilet=guest toilet
gør=do(es) / make(s)
gøre=to do / to make
haft=had
halvanden=one and a half
ham=him
han=he
handelsby=market town
handler=is about / shop(s)
hans=his
har=has / have
havde=had
have=garden / to have
haven=the garden
havnen=the harbour
hedder=is called
hej=hi
heldig=lucky
heldigvis=fortunately
hele=whole / all
heller=either (heller ikke = not either)
hellere=rather
helst=preferably
helt=completely
hen=(to a place)
hende=her
hendes=her
hente=to pick up
henvisninger=references
her=here
herefter=after this
hertil=in addition to this
herunder=including
hilsen=greeting / regards
hilsner=greetings / regards
hinanden=each other
hindbærsnitter=raspberry slices
historie=history / story
hits=hits
hjalp=helped
hjem=home
hjemland=home country
hjemme=at home
hjemmearbejde=working from home
hjemmebesøg=home visit
hjemmefra=from home
hjemmet=the home
hjul=wheels
hjælpe=to help
hjælpemidler=aids (allowed materials)
hjælpen=the help
hmm=hmm
hobby=hobby
hobbyer=hobbies
hold=team / class
holde=to hold / to keep
holder=hold(s) / keep(s)
holdet=the class / the team
holdningstekst=opinion text
holdt=held / kept
hos=at (someone's place)
huller=gaps / holes
hullerne=the gaps
hullet=the gap
hun=she
hund=dog
hunde=dogs
hurtig=quick
hurtigere=faster
hurtigt=quickly
hus=house
huset=the house
husets=the house's
husk=remember
husleje=rent
hvad=what
hvem=who
hver=each / every
hverdag=weekday / everyday life
hverdage=weekdays
hverdagen=everyday life
hverdagslivet=everyday life
hvert=each / every
hvide=white
hvidløg=garlic
hvilke=which
hvilken=which
hvilket=which
hvis=if
hvor=where / how
hvordan=how
hvorfor=why
hvorfra=from where
hvornår=when
hyggelig=cosy / nice
hyggelige=cosy / nice
hyggeligt=cosy / nice
hygger=have a nice time
håber=hope(s)
håndpillede=hand-peeled
håndvægte=hand weights
håndværker=craftsman
håndværkerne=the workmen
hænger=hang(s)
hæver=rise(s)
hævet=raised
høj=high / loud
høje=high
hør=listen / hear
høre=to hear / to listen
hører=hear(s) / belong(s)
i=in / you (plural)
idrætshal=sports hall
idé=idea
ifølge=according to
igen=again
igennem=through
ikke=not
ind=in / into
indbyggede=built-in
indehaverne=the owners
indeholder=contains
inden=before
indflytningsklar=ready to move into
indføring=introduction
indført=introduced
indholdet=the content
indkøb=shopping
indkøbsmuligheder=shopping facilities
indledning=introduction
indlæg=article / contribution
indre=inner
indretning=interior design / layout
indrettede=furnished / decorated
indsætte=to insert
influenza=flu
info=info
information=information
informationen=the information
informationer=information
informationstekst=information text
ingen=no / none / nobody
ingeniør=engineer
inspireret=inspired
institutioner=institutions (nurseries etc.)
instruktionen=the instructions
intens=intense
interessant=interesting
internettet=the internet
interview=interview
interviewet=the interview
inversion=inversion (verb before subject)
invitationen=the invitation
inviteret=invited
irritere=to annoy
især=especially
it-konsulent=IT consultant
italienske=Italian
ja=yes
jakke=jacket
jakken=the jacket
jeg=I
jer=you (plural)
jeres=your (plural)
jo=you know / after all
job=job
jobansøgning=job application
jobbet=the job
jul=Christmas
julefrokost=Christmas lunch
jævnligt=regularly
kaffe=coffee
kaffebrød=coffee cakes
kaffemaskine=coffee machine
kager=cakes
kalorier=calories
kampen=the fight
kan=can
kanelsnegle=cinnamon rolls
kanelting=cinnamon pastries
karakter=grade
kassen=the till / checkout
kedeligt=boring
kende=to know
kender=know(s)
kendt=known
kendte=knew
kigge=to look
kigger=look(s)
kilde=source
kip=ridge (roof)
kl=o'clock (kl. = time)
kladde=draft
klage=complaint / to complain
klager=complain(s)
klar=ready / clear
klaret=done / managed
klasse=class / grade
klasser=classes
klassiske=classic
klik=click
klinker=tiles
knasende=crunchy
kogehalvø=kitchen peninsula
kohærens=coherence
kohæsion=cohesion
kokossnitter=coconut slices
koldt=cold
kollega=colleague
kolleger=colleagues
kollegerne=the colleagues
kollegiet=the student residence
kollegium=student residence
kom=came / come
kombinerede=combined
komme=to come
kommer=come(s)
kommune=municipality
kommunen=the municipality
komparativ=comparative
koncentrere=to concentrate
kondition=fitness
konditionen=the fitness
konditionstræning=cardio training
kone=wife
kongens=the king's
konsistensen=the texture
kontakt=contact
kontakte=to contact
kontant=cash price
kontor=office
kontoransatte=office workers
kontoret=the office
koordinationen=the coordination
kop=cup
kort=short / card / map
korte=short
koster=costs
kr=kroner (DKK)
kransekage=marzipan ring cake
kredsløbet=the circulation
kredsløbstræning=circuit training
kriterier=criteria
kriterierne=the criteria
kroner=kroner (Danish currency)
krop=body
kroppen=the body
kroppens=the body's
krops=body's
kropsbevidsthed=body awareness
kropsbevidstheden=the body awareness
kræver=require(s)
kun=only
kunder=customers
kunderne=the customers
kunne=could
kunsten=the art / the trick
kvalitet=quality
kvarter=neighbourhood / quarter of an hour
kvinde=woman
kvindehold=women's class
kvinden=the woman
kvinder=women
kvittering=receipt
kælder=basement
kælderen=the basement
kære=dear
kæreste=boyfriend / girlfriend
kærlighed=love
kærligheden=love
køb=buy / purchase
købe=to buy
køber=buy(s) / buyer
købet=the purchase
købmandsbutik=grocery shop
købt=bought
køge=Køge (town)
køges=Køge's
køkken=kitchen
køkken-alrum=kitchen-family room
køkkenbordet=the kitchen table
køkkenet=the kitchen
køleskab=fridge
køre=to drive
kørekort=driving licence
kører=drive(s)
kørsel=driving
kørt=driven
kørte=drove
lade=let
land=country / countryside
lande=countries
landet=the country / the countryside
landligt=rural
landsby=village
landsbyen=the village
lange=long
langs=along
langt=far / long
larm=noise
lastbil=lorry / truck
lastbilchauffør=lorry driver
latinamerikanske=Latin American
latinerkvarteret=the Latin Quarter
lav=make / low
lave=to make / to do
lavede=made / did
laver=make(s) / do(es)
laves=be made
lavet=made
led=joints
ledes=is led
ledet=led
ledsætninger=subordinate clauses
lege=to play
legende=legend
legevenlig=good for playing
lejlighed=apartment
lejligheder=apartments
lejlighederne=the apartments
lektiehjælp=homework help
lektier=homework
let=easy / light
lette=easy
leve=to live
lide=(kan lide = like)
lidt=a little
lige=just / straight / equal
ligesom=like / just as
ligger=lies / is located
ligner=resemble(s)
lille=small
lingvistisk=linguistic
linje=line
linjen=the line
live-feedback=live feedback
live-tekst=live text
liv=life
livstruende=life-threatening
loft=ceiling
loftsrum=attic room
lokalerne=the premises
lov=permission / law
luft=air
lukkes=be closed
lukket=closed
lyder=sounds
lynlåsen=the zip
lys=light / bright
lyse=light / bright
lyset=the light
lyst=bright / desire
lytter=listening
lår=thighs
lås=unlock (lås op)
læben=the lip
læge=doctor
lægehuset=the doctor's surgery
lægen=the doctor
lægevagten=the out-of-hours doctor service
lækkert=delicious / lovely
længe=long (time)
længere=longer
lær=learn
lære=to learn / to teach
lærer=teacher
læreruddannede=trained as a teacher
lært=learned
læs=read
læse=to read
læseforståelse=reading comprehension
læsehest=bookworm
læseopgaver=reading tasks
læsning=reading
læsser=load(s)
løb=run
løbe=to run
løbeklub=running club
løber=run(s)
lørdag=Saturday
løsne=to loosen
mad=food
maden=the food
madvaner=eating habits
mail=email
mailet=emailed
mails=emails
maj-juni=May–June
man=one / you (people in general)
mand=man / husband
mandag=Monday
mange=many
manglede=was missing / lacked
mangler=is missing / lacks
marengskager=meringue cakes
marker=fields
marmelade=jam
marts=March
masser=lots
match=match
matematik=mathematics
mave=stomach
mavebøjninger=sit-ups
med=with
medarbejderne=the employees
medborgerhuset=the community centre
medlemmer=members
meget=very / much
mellem=between
meltyper=types of flour
men=but
mener=think / mean
mening=opinion / meaning
mennesker=people
mens=while
mere=more
mest=most
meste=most
midt=in the middle
midtbybageren=the city-centre baker
midte=middle
mig=me
mikrofonen=the microphone
miljøvenlig=environmentally friendly
millioner=millions
min=my
mindre=smaller / less
mindst=at least
mine=my
minikager=mini cakes
minimum=minimum
minutter=minutes
minutters=minutes'
mit=my
mod=towards / against
modeller=models
modelsvar=model answer
modelsvaret=the model answer
modtageren=the recipient
monolog=monologue
mor=mother
morfologi=morphology (word endings)
morgen=morning
morgenen=the morning
morgenmad=breakfast
motion=exercise
motionsgymnastik=fitness gymnastics
motionshold=exercise classes
motorvejen=the motorway
muffins=muffins
mulighed=possibility / option
muligheder=possibilities / options
muligt=possible
mundtlig=oral
muret=bricked
musik=music
muskel=muscle
muskelgrupper=muscle groups
muskler=muscles
musklerne=the muscles
muskulaturen=the muscles
mål=goal / target
målet=the goal
målrettet=aimed at
måned=month
måneden=the month
måneder=months
mænd=men
mærke=to feel / to notice
møde=to meet / meeting
mødes=meet
mørke=dark
müsliboller=muesli rolls
nabo=neighbour
naboer=neighbours
naboerne=the neighbours
nabolaget=the neighbourhood
nakke=neck
natten=the night
naturen=nature
navn=name
navnet=the name
ned=down
nej=no
nemlig=you see / namely
nervøse=nervous
nettet=the net / the internet
niv=level (abbr.)
niveau=level
niveauer=levels
nogen=someone / any
noget=something / some
nogle=some
nok=enough / probably
normalt=normally
november=November
nr=no. (number)
nu=now
nulstil=reset
ny=new
nybegynder=beginner
nyder=enjoy(s)
nydes=be enjoyed
nye=new
nyeste=newest
nymalede=newly painted
nyt=new
nyttige=useful
nytår=New Year
nå=well / reach
når=when / reach(es)
nærheden=the vicinity
næste=next
næsten=almost
nævner=mention(s)
nødt=(være nødt til = have to)
nødvendigt=necessary
nøgle=key
nøglen=the key
nøjagtigt=exactly
offentlig=public
officielle=official
ofte=often
og=and
også=also
okay=okay
oksebryst=beef brisket
om=about / if / around
omgivelser=surroundings
områder=areas
ondt=pain (have ondt = be in pain)
onsdag=Wednesday
onsdagen=Wednesday
op=up
opbygge=to build up
opdagede=discovered
opfølgende=follow-up
opført=built
opgave=task
opgaverne=the tasks
opholdsafdeling=living area
opholdsstue=living room
opkaldt=named
oplagt=obvious
oprindelig=originally
opslag=notice / post
optage=to record
optagelse=recording
optagelsen=the recording
optimale=optimal
opvarmning=warm-up
ord=word(s)
ordantal=word count
ordantallene=the word counts
ordentligt=properly
ordjagt=word hunt
ordjæger=word hunter
ordklassen=the word class
ordre=order
ordrenummeret=the order number
ordsamler=word collector
ordsmed=wordsmith
ordstilling=word order
ordvalg=choice of words
organisering=organisation
os=us
ost=cheese
over=over / about
overdækket=covered
pakken=the parcel
panden=the forehead
par=couple / pair / a few
parat=ready
parken=the park
parkering=parking
parkeringsplads=car park
parret=the couple
passende=suitable
passer=fits / suits / looks after
penge=money
pengene=the money
pensionister=pensioners
perfekt=perfect
persisk=Persian
person=person
pige=girl
plads=space / place
plan=floor / level / plan
planlæg=plan
planlægge=to plan
planter=plants
pludselig=suddenly
point=points
pointene=the points
pragmatisk=pragmatic (does the text do its job?)
primært=primarily
pris=price
priser=prices / awards
problem=problem
problemer=problems
problemet=the problem
procent=percent
produkter=products
profil=profile
profiler=profiles
projektet=the project
præcise=precise
præsenter=introduce
præstation=performance
prøv=try
prøve=test / exam / to try
prøvede=tried
prøven=the test / the exam
prøver=tests / tries
prøvesæt=exam set
prøvesættet=the exam set
pulsen=the pulse
punkter=points
punktum=full stop
på=on / at
pæn=nice / neat
pænt=nicely / neat
rabat=discount
radioen=the radio
ramme=box / frame
rammer=frames / setting
rask=healthy / well
recept=prescription
redskaber=equipment
referenceramme=frame of reference
regler=rules
regner=rains / calculate
regnes=is calculated
rejer=prawns
rejse=to travel / journey
rejser=travel(s) / journeys
rekord=record
renovere=to renovate
rent=clean
reparation=repair (how easy the text is to understand)
repetition=repetition
replik=line (in a dialogue)
replikker=lines (in a dialogue)
restaurant=restaurant
ret=dish / right / quite
retorisk=rhetorical
retskrivning=spelling
rettenøgle=answer key
rigtig=right / really
rigtige=right / correct
rigtigt=right / true
rimer=rhymes
ring=call
ringe=to call / poor
ringer=call(s)
ristet=toasted
ro=peace / calm
rolige=quiet / calm
roligt=calm
rugbrød=rye bread
rulninger=rolls (exercise)
rum=rooms / room
rummelige=spacious
rummer=contains
rundt=around
rydder=tidies (rydde op = tidy up)
ryg=back
ryggen=the back
råd=advice / afford (have råd til)
rækker=rows
rød=red
røget=smoked
sager=things
sal=floor / hall
salg=sale
salsa=salsa
samarbejde=to cooperate
samarbejder=cooperate(s)
samba=samba
saml=collect
samlet=gathered / total
samme=same
sammen=together
sammenhængende=coherent
sammenlign=compare
samt=and / as well as
samtale=conversation
samtalen=the conversation
samtalepartner=conversation partner
sandwiches=sandwiches
savne=to miss
savner=miss(es)
scones=scones
se=see / look
sekretær=secretary
seks=six
sekunder=seconds
selv=self / even
selvfølgelig=of course
selvom=even though
sende=to send
sender=send(s)
senest=at the latest
seneste=latest
seng=bed
ser=see(s) / look(s)
ses=see each other
sidde=to sit
sidder=sit(s)
side=side / page
siden=since / the page
sidst=last
sidste=last
sig=himself / herself / themselves
sige=to say
siger=say(s)
signaler=signals
sikker=sure / safe
sikre=to ensure / safe
sin=his / her / its (own)
sind=mind
sine=his / her (own)
single=single
singler=singles
sit=his / her (own)
sjov=fun
sjovt=fun
skabe=cupboards / to create
skabes=is created
skader=injuries
skal=must / shall / will
skarpt=sharp (skyde med skarpt = go all out)
skidt=bad
skole=school
skoleelever=schoolchildren
skoleleder=head teacher
skolen=the school
skoler=schools
skov=forest
skoven=the forest
skriftlig=written
skriftlige=written
skriv=write
skrive=to write
skrivecoach=writing coach
skrivecoachen=the writing coach
skrivekarl=writer
skriveopgaven=the writing task
skriveopgaver=writing tasks
skriver=write(s)
skrivning=writing
skrue=turn (skrue ned = turn down)
skud=shot (skud på stammen = new addition)
skuffet=disappointed
skuldre=shoulders
skulle=should / was going to
skyder=shoot(s)
skærekager=sliced cakes
skøn=lovely / estimate
skønne=lovely
skønt=lovely
slet=at all (slet ikke = not at all)
slette=to delete
slog=struck (slog dørene op = opened)
slut=end / over
slutter=ends
smage=to taste
smagen=the taste
smagt=tasted
smidig=supple
smidighed=flexibility
smil=smile
smukke=beautiful
små=small
småkagefronten=the biscuit front
småkagehuset=the cookie house (bakery name)
småkager=biscuits / cookies
småreparationer=small repairs
snakke=to chat
snakkemester=chat master
snakker=chat(s)
snegle=cinnamon swirls
sofahygge=cosy time on the sofa
solen=the sun
solrig=sunny
solrige=sunny
som=as / like / who / that
somme=(somme tider = sometimes)
sommer=summer
sort=black
sortfodsskinke=Iberian ham
sortiment=range
sove=to sleep
soveværelser=bedrooms
spansk=Spanish
sparer=save(s)
specialbrød=speciality bread
spelt=spelt
spidsen=the head / the top
spil=play / game
spise=to eat
spiseplads=dining area
spiser=eat(s)
spisestue=dining room
spisning=eating / dining
sport=sport
spring=skip (spring over)
sprogcafé=language café
sprogcenter=language centre
sprogskole=language school
sprogskolen=the language school
sprogskolens=the language school's
sprængt=salt-cured
spændende=exciting
spændinger=tensions
spørg=ask
spørger=ask(s)
spørgsmål=question(s)
spørgsmålene=the questions
spørgsmålet=the question
squats=squats
stadig=still
stammen=the trunk (skud på stammen = new addition)
stand=condition
start=start
starte=to start
starter=start(s)
startes=be started
startet=started
staten=the state
stationen=the station
stavning=spelling
sted=place
steder=places
stedet=the place
steget=risen
stenovnsbagte=stone-oven baked
stikord=keywords / notes
stil=style
stille=quiet / to put
stiller=put(s) / place(s)
stop=stop
stoppe=to stop
stopper=stops
stor=big
storbyens=the big city's
store=big
stort=big
straks=immediately
strammet=tightened / toned
strand=beach
stranden=the beach
stress=stress
stribe=strip / series
struktur=structure
stræk=stretches
strømmer=streams
studenterbrød=student bread (cake)
studerer=study / studies
stue=living room
stueetagen=the ground floor
stuen=the living room
stueplan=ground floor
stueplanets=the ground floor's
stuer=living rooms
stykker=pieces (i stykker = broken)
styrke=strength / to strengthen
styrket=strengthened
stået=stood
står=stand(s) / is written
stærk=strong
større=bigger
størrelse=size
største=biggest
støv=dust
succes=success
suite=(en suite = connected rooms)
sund=healthy
sundhed=health
sundhedskort=health insurance card
sundhedskortet=the health insurance card
sundhedssystem=health system
sundt=healthy
supermarkedet=the supermarket
sur=angry / sour
surdej=sourdough
svag=weak
svar=answer
svarer=answer(s)
svaret=the answer
sved=sweat
sværere=harder
svært=difficult
svømme=to swim
svømmehal=swimming pool
svømmehold=swimming class
sydvendt=south-facing
syg=ill / sick
sygdom=illness
synes=think / feel
synspunkter=points of view
syntaks=syntax (sentence structure)
syv=seven
så=so / then / saw
sådan=like that / such
såkaldte=so-called
sælgeren=the seller
sælges=for sale
særdeles=extremely
særskilt=separate
sætning=sentence
sætningen=the sentence
sætninger=sentences
sætningsbygger=sentence builder
sætningslængde=sentence length
sætningsstarter=sentence openings
sætter=put(s) / set(s)
sød=sweet / nice
søde=sweet
søge=to apply / to search
søger=seek(s) / looking for
søn=son
søndag=Sunday
sørger=make(s) sure
tag=roof / take
tage=to take
tager=take(s)
taget=taken / the roof
tagterrasse=roof terrace
tak=thanks
tal=speak / number
tale=speaking / to speak / speech
taleopgaver=speaking tasks
taletid=speaking time
taletiden=the speaking time
taleøvelserne=the speaking exercises
talt=spoken
talte=spoke
tanken=the petrol station / the thought
tankstationer=petrol stations
tebirkes=poppy-seed pastries
tegnsætning=punctuation
tekst=text
teksten=the text
tekster=texts
teksterne=the texts
telefonen=the phone
telefonnummeret=the phone number
tema=theme
tempo=pace
terrasse=terrace / patio
terrassemiljø=patio area
terrasser=terraces
tester=tests
tid=time
tiden=the time
tider=times
tidernes=(i tidernes løb = over time)
tidligere=earlier / previously
tidligt=early
til=to / for
tilbage=back
tilbud=offers / facilities
tilfreds=satisfied
tilfredse=satisfied
tilfældigt=random
tillader=allows
tilmelde=to sign up
tilmelding=registration
tilpasser=adapts
tilrettet=adapted
time=hour / lesson
timen=the lesson / the hour
timer=hours / timer
ting=things
tip=tip
tirsdage=Tuesdays
tit=often
tjek=check
tjener=earn(s)
tlf=phone (tlf.)
to=two
tog=train / took
toget=the train
togstationen=the train station
toilet=toilet
tomat=tomato
tomater=tomatoes
tonen=the tone
torsdag=Thursday
torv=square (town square)
tradition=tradition
traditioner=traditions
traditionsrige=traditional
trafik=traffic
transport=transport
transportfirma=transport company
trappe=stairs
tre=three
tredje=third
trinene=the steps
trins-skalaen=(7-trins-skalaen = the 7-point grading scale)
tror=think / believe
trygt=safe
tryk=press
tråd=thread (rød tråd = common thread)
træk=draw / pull (i træk = in a row)
trække=to pull / to go out
træn=train / practise
træne=to train / to exercise
træner=train(s) / trainer
trænet=trained
træning=training
træningen=the training
træt=tired
træterrasse=wooden terrace
tunesiske=Tunisian
tur=trip / walk
turde=dared
ture=trips
tusind=thousand
tv=TV
tydeligt=clearly
type=type
typer=types
tyskland=Germany
tærter=tarts
tæt=close
tøj=clothes
tømrer=carpenter
ud=out
udbydes=is offered
uddannelse=education
uddrag=extract
ude=out / outside
udekøkken=outdoor kitchen
udelivet=outdoor life
uden=without
udestue=conservatory
udestuen=the conservatory
udflugt=trip / excursion
udfolde=to unfold
udfordrende=challenging
udfordringer=challenges
udfyld=fill in
udfyld-hullerne=fill in the gaps
udgang=exit / access
udhus=shed
udlandet=abroad
udover=besides
udsigt=view
udstræk=stretching
udstrækning=stretching
udstyr=equipment
udtrykke=to express
udvalg=selection
udvalget=the selection
uge=week
ugen=the week
uger=weeks
ulejligheden=the inconvenience
ulempe=disadvantage
ulemper=disadvantages
ulykke=accident
ulykker=accidents
under=under / during
undersøge=to investigate
undersøgelse=study / survey
undervisningen=the lessons / teaching
unge=young people
ungt=young
universitet=university
usundt=unhealthy
utilfreds=dissatisfied
vafler=waffles
var=was / were
varer=goods / lasts
varet=lasted
varianten=the variant
variation=variation
varierede=varied
varierer=varies
varme=warmth / heat
varmer=warm(s)
varmet=warmed
vaskemaskine=washing machine
vasker=wash(es)
vaskerum=laundry room
vaskesøjle=washer-dryer stack
ved=at / by / know(s)
vedligeholde=to maintain
vej=road / way
veje=roads / to weigh
vejene=the roads
vejledende=guiding / recommended
vejret=the weather
velholdt=well-maintained
velholdte=well-maintained
velkommen=welcome
velkomne=welcome
velvalgt=well-chosen
ven=friend
vendinger=phrases / expressions
venlig=kind
vennen=the friend
venner=friends
vente=to wait
verbernes=the verbs'
verbet=the verb
verden=the world
verdener=worlds
version=version
vest=west
vestjylland=West Jutland
vi=we
vide=to know
videre=on / further
vigtig=important
vigtigere=more important
vigtigt=important
vil=want(s) / will
villa=detached house
villaen=the house
ville=would / wanted
vinde=to win
vinduer=windows
vinduerne=the windows
vindueskarmene=the windowsills
vinduespartier=window sections
vinkelstue=L-shaped living room
vinterjakke=winter jacket
virker=works / seems
virksomheder=companies
viser=shows
voksne=adults
vores=our
vundet=won
vurdere=to assess
vurderer=assess(es)
vurdering=assessment
våde=wet (våde varer = drinks)
væk=away
vælg=choose
vælge=to choose
vælger=choose(s)
vær=be
værd=worth
være=to be
værelse=room
værelser=rooms
værelset=the room
været=been
værste=worst
webbutik=online shop
webbutikken=the online shop
weekenden=the weekend
yderligere=further / additional
ydervægge=outer walls
yngre=younger
yoga=yoga
yogastillinger=yoga poses
zumba=zumba
åben=open
åbent=open
åbne=open
åbnede=opened
år=year(s)
året=the year
årets=the year's
års=year's (40-års = 40th)
årsagen=the reason
ås=ridge
æble-kanel=apple-cinnamon
æbler=apples
ægteparret=the married couple
ægteparrets=the married couple's
ældste=oldest
ærlig=honest
én=one
øge=to increase
øges=is increased
øget=increased
ølandshvede=Øland wheat
ønsker=wish(es)
øv=practise
øve=to practise
øvede=practised / experienced
øvelser=exercises
øvelserne=the exercises
øvemål=practice target
øvet=practised
øvrige=other / remaining
aerobichold=aerobics class
folk=people
oktober=October
placering=placement / position
sfo=after-school club (SFO)
vane=habit
schweizerdeli=Swiss deli
comté-ost=Comté cheese
chilimayo=chilli mayo
mobilepay=MobilePay (Danish payment app)
københavn=Copenhagen
syrien=Syria
iran=Iran
odense=Odense (city)
esbjerg=Esbjerg (city)
vestby=Vestby (town)
streak=streak (days in a row)
xp=XP (experience points)
opgaver=tasks
løst=solved
holdningstekster=opinion texts
bedømmelse=assessment
bedømt=assessed
oplæsning=reading aloud
emner=topics
prøvetid=exam time
rammen=the box / the frame
set=seen
situationen=the situation
ad=along / down (ned ad = down)
pd=PD (Prøve i Dansk)
co=co. (and company)
www=www (web address)
ida=(a name)
frank=(a name)
anna=(a name)
tom=(a name)
toms=(a name)
jessen=(a name)
mette=(a name)
holm=(a name)
amir=(a name)
sofia=(a name)
jonas=(a name)
hansen=(a name)
leilas=(a name)
sara=(a name)
jensen=(a name)
peter=(a name)
ali=(a name)
maria=(a name)
lopez=(a name)
hanne=(a name)
tran=(a name)
ahmed=(a name)
karimi=(a name)
fatima=(a name)
berg=(a name)
jens=(a name)
lise=(a name)
nielsen=(a name)
maja=(a name)
karen=(a name)
husted=(a name)
christian=(a name)
funder=(a name)
tine=(a name)
lajer=(a name)
petersen=(a name)
lars=(a name)
karin=(a name)
lone=(a name)
klemmenstrupvej=(street name)
hasselvej=(street name)
kildevej=(street name)
ølbyvej=(street name)
langesvej=(street name)
vordingborgvej=(street name)
egevej=(street name)
stormøllevej=(street name)
smedevej=(street name)
køgevej=(street name)
lidemarksvej=(street name)
mejlgade=(street name)
åboulevarden=(street name)
graven=(street name)
ølby=(place name)
ulstrup=(place name)
lidemark=(place name)
valløskovene=(place name)
frederiksbjerg=(place name)
åbyhøj=(place name)
briancon=(business / website name)
schweizerbageriet=(business / website name)
tøjnet=(business / website name)
friskkøb=(business / website name)
jobindex=(business / website name)
boligvest=(business / website name)
smagaarhus=(business / website name)
nowruz=Nowruz (Persian New Year)
bruuns=(part of a street name)
frederiks=Frederik's (street name)
ak=AK (name of the evening school)
aerobic=aerobics
administration=administration
administrative=administrative
afdeling=department
afgifter=taxes / duties
afskaffer=abolish(es)
aften=evening
aktuelle=current
alder=age
aldersgrænse=age limit
allerede=already
almindelig=ordinary / normal
altanerne=the balconies
alternativt=alternative
alvorligt=seriously
ambitiøs=ambitious
analysere=to analyse
anderledes=different(ly)
anmode=to request (anmode om)
annoncer=advertisements
ansvar=responsibility
ansætte=to employ / to hire
ansøgninger=applications
apps=apps
arbejdsliv=working life
arbejdsmailen=the work email
arbejdsplads=workplace
arbejdspladsen=the workplace
arbejdstid=working hours
arbejdsuge=working week
argument=argument
argumentation=argumentation
argumenter=argue / arguments
argumentere=to argue
argumenterende=argumentative
argumenterer=argue(s)
artikel=article
artikler=articles
babysvømning=baby swimming
badede=bathed / swam
bageren=the baker's
baggrund=background
balancen=the balance
banket=knocked / hammered
barn=child
barnet=the child
barnets=the child's
beboer=resident
beboermøde=residents' meeting
begrunde=to justify / give reasons
begår=commit(s) / make(s) (mistakes)
beholde=to keep
bekymrede=worried
bekymring=concern / worry
beløb=amount
besked=message
beskeder=messages
besluttede=decided
bestyrelsen=the board
besvare=to answer
betyde=to mean
betydet=meant
bevæget=moved
bidrage=to contribute
billetsystemer=ticket systems
billigt=cheap(ly)
blå=blue
boet=lived
boligområder=residential areas
boligorganisation=housing organisation
bondehus=farmhouse
borde=tables
boret=drilled
breve=letters
brugen=the use
bruges=is used
budget=budget
budgettet=the budget
buskort=bus pass
busser=buses
byggeri=construction
byggeriet=the construction site
byrådet=the town council
bøger=books
bør=should / ought to
børns=children's
cafeerne=the cafés
cyklede=cycled
cykelværksted=bicycle repair shop
dannelse=education / formation (digital dannelse = digital literacy)
danskprøver=Danish tests
data=data
debat=debate
deltagelse=participation
deltaget=taken part
demokrati=democracy
demokratiet=democracy
dermed=thereby / thus
desto=(ikke desto mindre = nevertheless)
digital=digital
diskussion=discussion
diskuter=discuss
diskutere=to discuss
disse=these
droppet=dropped
drømte=dreamed
dyr=expensive / animal
dårligere=worse
dårligt=bad(ly)
dæk=tyre
dør=door
døren=the door
efterhånden=gradually
efterlyse=to call for
efterlyser=call(s) for
eftersom=since / as
efteruddannelse=further training
egenskab=quality / trait
egenskaber=qualities
ekspedient=shop assistant
ekstern=external
elev=pupil / student
elever=pupils
ender=end(s) up
ene=one (på den ene side = on the one hand)
enkel=simple
enkle=simple
erhverv=business / trade
etværelseslejlighed=one-room flat
fag=subject(s)
fagforeningerne=the trade unions
faglig=academic / professional
fagligt=academically
farlig=dangerous
farve=colour
farvel=goodbye
fat=hold (få fat i = get hold of)
fattige=poor
feber=fever
feedbacken=the feedback
fejl=mistake(s) / error(s)
festudvalget=the party committee
fik=got / received
film=film(s)
findes=exists / be found
firedages=four-day
fjerner=remove(s)
fladt=flat
fleksibel=flexible
flyrejser=air travel / flights
flyt=move
flytningen=the move
fodbold=football
fokusere=to focus
fokuserer=focus(es)
folkeskolen=the public school (primary and lower secondary)
forbruger=consumer
forbud=ban
forbyde=to ban
forbydes=be banned
foregår=takes place
forening=association / club
foreningen=the association
foreningslivet=club and association life
forestille=to imagine (forestille sig)
forhandl=negotiate
forhandle=to negotiate
forkerte=wrong
forklare=to explain
form=form / shape
formel=formal
formelle=formal
formiddag=morning (before noon)
fornavn=first name
fornuftigt=sensibly
forskel=difference
forskere=researchers
forskerne=the researchers
forskning=research
forskningslaboratorierne=the research laboratories
forslag=proposal / suggestion
forslaget=the proposal
forstyrrer=disturb(s)
forståelse=understanding
forstået=understood
forstår=understand(s)
forsvinder=disappear(s)
fortjener=deserve(s)
fortryde=to regret
fortryder=regret(s)
forvirring=confusion
forælder=parent
franskbrød=white bread
frikvarterer=breaks (at school)
frikvartererne=the breaks
frisør=hairdresser
frister=tempt(s)
fritidsaktiviteter=leisure activities
frivillig=volunteer / voluntary
fungerer=work(s) / function(s)
fylde=to fill
fyraften=end of the working day
fyret=fired
fysik=physics
fælde=to cut down (trees)
fællesskab=community / togetherness
færdigheder=skills
færdigt=finished
færre=fewer
føler=feel(s)
gaden=the street
galt=wrong (hvad er der galt = what's wrong)
gamle=old
gammelt=old
generalforsamlingen=the general meeting
giv=give
gjort=done / made
glemme=to forget
glemt=forgotten
glæder=look(s) forward (glæder sig)
grillen=the barbecue
griner=laugh(s)
grundlag=foundation / basis
grupper=groups
grå=grey
grænserne=the limits
grønne=green
gymnasielærer=upper-secondary school teacher
gymnasierne=the upper-secondary schools
gymnastikforening=gymnastics club
gården=the courtyard
gårdfest=courtyard party
gøres=be done
halsen=the throat
halv=half (halv ni = half past eight)
halvdelen=half
halvt=half
handle=to shop / to act
hav=have (hav en god dag = have a nice day)
hel=whole
henter=pick(s) up
henvende=to contact (henvende sig)
henvendelser=enquiries
henvender=contact / approach
henvis=refer
herfra=from here
hermed=hereby
herreklip=men's haircut
hjemmesiden=the website
hjælp=help
hjælper=help(s)
hk=HK (a trade union)
holdbarhed=shelf life / durability
holdbarhedsdatoerne=the best-before dates
holdning=opinion / attitude
holdninger=opinions
hovedstaden=the capital
hul=gap / hole
hundrede=hundred
hundredtusindvis=hundreds of thousands
huse=houses
huske=to remember
huslejen=the rent
hverdagsdansk=everyday Danish
hverdagsliv=everyday life
hverdagstekster=everyday texts
hvorefter=after which
hvorhen=where to
hvorimod=whereas
håndtere=to handle
hårdt=hard
hævde=to claim
højere=higher
højre=right (til højre = to the right)
hørt=heard
imellem=between
imidlertid=however
imod=against
indbyggere=inhabitants
inddrag=include / involve
inddrage=to involve
inddrager=involve(s)
inde=inside (låst inde = locked away)
indendørs=indoors
indhold=content
indkomst=income
integration=integration
integrationen=the integration
intelligens=intelligence (kunstig intelligens = AI)
interesse=interest
investerer=invest(s)
investering=investment
journalist=journalist
journalistik=journalism
jobportalen=the job portal
kage=cake
kalder=call(s)
kandidatgrad=master's degree
karakterer=grades / marks
karaktererne=the grades
karakterfri=without grades
kedelige=boring
kirken=the church
klagede=complained
klare=clear / to manage
klarer=manage(s) / cope(s)
klima=climate
klimaet=the climate
klimaets=the climate's
klimaproblemerne=the climate problems
klimavenlige=climate-friendly
klip=haircut / cut
knap=just under / barely
knus=hugs
kold=cold
kommet=come
kommunens=the municipality's
kommunikationsmedarbejder=communications officer
kommunikere=to communicate
kompromis=compromise
konkluderer=conclude(s)
konklusion=conclusion
konkret=concrete / specific
konkrete=concrete / specific
kontrol=control / checks
kontrollerer=check(s)
korrekte=correct
kostede=cost
kraftig=powerful / loud
krav=requirement / demand
kreativ=creative
kritikerne=the critics
krævede=required
kultur=culture
kundehenvendelser=customer enquiries
kundeservicemedarbejder=customer service worker
kunstig=artificial
kursus=course
kurven=the basket
kvadratmeter=square metres
kvaliteten=the quality
købte=bought
kød=meat
lad=let (lad os = let's)
lang=long
langsomt=slowly
larmen=the noise
larmer=make(s) noise
larmes=noise is made
ledelsen=the management
leder=manager / leader
legetøj=toys
lejligheden=the apartment
lettere=easier
ligeud=straight ahead
listen=the list
livet=life
livret=favourite dish
livsstil=lifestyle
lokal=local
lokalavis=local newspaper
lokale=local
lokalsamfund=local community
lokalsamfundet=the local community
lommen=the pocket
loppemarked=flea market
luftforurening=air pollution
låst=locked
lægger=put(s) / place(s) (lægge vægt på = emphasise)
lærere=teachers
læreren=the teacher
læring=learning
læringen=the learning
lærte=learned
læser=read(s) / reader
læserbrev=letter to the editor
læst=read
løn=salary / pay
lønforhøjelse=pay rise
lørdage=Saturdays
lørdags=(i lørdags = last Saturday)
løse=to solve
løses=be solved
løsning=solution
løsninger=solutions
madspild=food waste
malet=painted
mandag-fredag=Monday to Friday
maskiner=machines
maskinerne=the machines
medarbejdere=employees
medarbejdernes=the employees'
medier=media
medmindre=unless
mellemstor=medium-sized
menneske=human being / person
meter=metre(s)
miljø=environment
mindske=to reduce
mindste=smallest (i det mindste = at least)
mister=lose(s)
mobilfri=mobile-free
mobiltelefoner=mobile phones
modargument=counterargument
modsætning=contrast (i modsætning til = unlike)
mundtligt=orally
myldretiden=rush hour
myndigheder=authorities
må=may / must
måde=way
måler=measure(s)
måtte=had to / might
mængderabatter=bulk discounts
møder=meetings / meet(s)
mørkt=dark
nabobyen=the neighbouring town
nedenfor=below
nedsat=reduced
nemmeste=easiest
nervøs=nervous
ni=nine
nuværende=current
nyhedsbrev=newsletter
nyhedsbreve=newsletters
nysgerrig=curious
offentlige=public
omstilling=transition (grøn omstilling = green transition)
opdaterer=update(s)
opefter=upwards
opfinde=to invent / make up
opgangen=the stairwell
oplever=experience(s)
oplysninger=information
oplægsholder=speaker / presenter
opmærksomheden=the attention
opslagstavlen=the noticeboard
opstår=arise(s) / occur(s)
otte=eight
overbevist=convinced
overflødig=redundant / superfluous
overflødige=redundant
overrasket=surprised
overskredet=exceeded
overskride=to exceed
overskudsmad=surplus food
overveje=to consider
overvejer=consider(s)
paraply=umbrella
paraplyen=the umbrella
parkere=to park
parkeringspladser=parking spaces
passe=to look after / to fit
patienter=patients
peger=point(s) (pege på = point out)
pensionist=pensioner
personer=people / persons
personlige=personal
plejecenter=care home
plejehjem=nursing home
plus=plus
pointe=point
politiker=politician
politikerne=the politicians
pose=bag
presset=pressured
prisen=the price
programmør=programmer
præcist=precisely
prøverne=the exams
prøvet=tried
påvirker=affect(s)
rapport=report
rapporten=the report
rapporter=reports
redaktør=editor
reducere=to reduce
regeringen=the government
regne=to rain
regnede=rained
relevante=relevant
reparerer=repair(s)
restauranter=restaurants
resten=the rest
resultater=results
resultatet=the result
retfærdig=fair
retningslinje=guideline
retningslinjer=guidelines
rimelig=reasonable
rimeligt=reasonable
ringere=worse / poorer
risici=risks
rolle=role
rutineopgaver=routine tasks
rygning=smoking
sad=sat
saftevand=squash (fruit drink)
sagen=the matter / the case
samfund=society
samfundet=society
samfundsemner=social issues
sammenlignende=comparative
sammenligner=compare(s)
sammenlignet=compared
sammenligning=comparison
samtaler=conversations
samtidig=at the same time
selvstændighed=independence
selvstændigt=independently
sendt=sent
senere=later
september=September
sikkert=probably / safely
skab=cupboard / locker
skaber=create(s)
skabt=created
skinnede=shone
skolebørn=schoolchildren
skoledagen=the school day
skoleforsker=school researcher
skolegården=the schoolyard
skoletid=school hours
skoletiden=school hours
skraldespanden=the bin
skygger=shade(s)
skyld=sake (for … skyld = for the sake of)
skåret=sliced
skærm=screen
skærmen=the screen
skærmtid=screen time
slukke=to turn off
slukket=switched off
smartphone=smartphone
smartphones=smartphones
smider=throw(s) (smide ud = throw away)
sms=text message
snart=soon (så snart = as soon as)
sne=snow
sociale=social
sofa=sofa
sofaen=the sofa
spild=waste
spille=to play
spiller=play(s)
spiselig=edible
spiste=ate
sproget=the language
sprogkrav=language requirement
spørge=to ask
startede=started
starten=the start
statsborgerskab=citizenship
steg=rose
stemme=to vote / voice
stemmer=vote(s)
stillet=put / asked (stillet krav = made demands)
stilling=position (job)
stillingen=the position
stillinger=positions
stod=stood (stod op = got up)
stole=chairs
storby=big city
stramt=tight
strategi=strategy
stresset=stressed
struktureret=structured
studerende=student(s)
styre=to control / to steer
stå=stand
stærke=strong
støj=noise
størst=biggest
støtte=to support
støtter=support(s)
su=SU (Danish student grant)
succesfulde=successful
sukker=sugar
sundhedssystemet=the health system
sundhedsudfordring=health challenge
supermarkeder=supermarkets
supermarkedernes=the supermarkets'
svare=to answer
sværeste=hardest
syge=ill / sick
sygeplejerske=nurse
sygt=ill / sick
synspunkt=point of view
system=system
systemer=systems
systemerne=the systems
sælg=sell
sælge=to sell
sælger=sell(s) / seller
sænkes=be lowered
sætte=to put / to set
søgning=search
taler=speak(s) / speaker
talsperson=spokesperson
tand=tooth
tandlæge=dentist
tandlægen=the dentist
tandlægerne=the dentists
tankegange=ways of thinking
taske=bag
te=tea
teams=teams
teknik=technical services
teknologi=technology
teknologien=the technology
tekstsammenhæng=text coherence
telefon=phone
telefonerne=the phones
temadag=theme day
temadage=theme days
temadagen=the theme day
ti=ten
tidligst=at the earliest
tidsbestilling=appointment
tilbyder=offer(s)
timers=hours'
tobak=tobacco
tons=tonnes
trafikken=the traffic
trafikuheld=traffic accidents
trivsel=well-being
troværdig=credible
troværdige=credible
trygge=safe / secure
træer=trees
træerne=the trees
trætte=tired
tvivle=to doubt
typisk=typical(ly)
tænder=light(s) / turn(s) on
tænker=think(s)
tænkt=thought
uddannelsen=the education
uddannelserne=the educational programmes
uddannelsessystemet=the education system
uddybe=to elaborate on
udenad=by heart
udfordring=challenge
udgift=expense
udleveres=be handed out
udsagn=statement(s)
udslippet=the emission(s)
udtryk=expression
udviklingen=the development
uenig=in disagreement
uenighed=disagreement
uklar=unclear
ukrainske=Ukrainian
understrege=to emphasise
understreger=emphasise(s)
undersøgelser=studies / surveys
undersøger=investigate(s)
undervise=to teach
undgå=to avoid
undskyld=sorry
universitetet=the university
usund=unhealthy
utilfredse=dissatisfied
utæt=leaky
valg=choice / election
valgretsalderen=the voting age
varm=warm
vejen=the road / the way
vennerne=the friends
venstre=left (til venstre = to the left)
viden=knowledge
video=video
vinteren=the winter
virkelig=really
virket=worked
virksomhed=company
virksomhederne=the companies
vist=shown
vågner=wake(s) up
vægt=weight / emphasis
weekend=weekend
årstid=season
årstiderne=the seasons
ældreplejen=elderly care
ændrede=changed
ændret=changed
økonomimedarbejder=finance officer
øl=beer
aalborg=Aalborg (city)
nørrebro=Nørrebro (part of Copenhagen)
vejle=Vejle (city)
teheran=Tehran
ukraine=Ukraine
sydfyn=South Funen (region)
søndergade=(street name)
torvet=the square
adam=(a name)
ahmadi=(a name)
amina=(a name)
anne=(a name)
birgitte=(a name)
henrik=(a name)
ivan=(a name)
karim=(a name)
kovalenko=(a name)
lene=(a name)
lina=(a name)
line=(a name)
mia=(a name)
mohammed=(a name)
morten=(a name)
mortensen=(a name)
mortensens=(a name)
nadia=(a name)
olena=(a name)
omar=(a name)
pia=(a name)
rahimi=(a name)
rasmus=(a name)
reza=(a name)
saleh=(a name)
signe=(a name)
sofie=(a name)
yusuf=(a name)
danskklar=DanskKlar ("ready for Danish")
niveauerne=the levels
sagt=said (kort sagt = in short)
uofficielt=unofficial
øveprogram=practice program
afholder=hold(s) (exams)
is=ice cream / ice
sommeren=the summer
a-g=A to G
a-f=A to F
motivationen=the motivation
computere=computers
solidt=solid
`;
