// Danish → English glossary used by the hover translator (js/translate.js).
// One entry per line: word=translation. Keys are lowercase word forms exactly
// as they appear in the app. Add a line here when you add new content.
PD2.GLOSSARY_RAW = `
a-h=A to H
aarhus=Aarhus (city)
acceptabel=acceptable
adgang=access
adjektiv=adjective
adressen=the address
af=of / by / from
afbud=cancellation (saying you can't come)
afhængig=dependent
afhængighedsskabende=addictive
aflevere=to hand in / to deliver
aflyse=to cancel
afskedsfest=farewell party
afslut=finish
afslutning=ending / conclusion
afslutter=finish / end
afsluttes=is finished / ends
afslører=reveals
afsnit=paragraph / section
afspænding=relaxation
aftale=appointment / agreement
aftaler=agree / arrange
aftenen=the evening
aftenkaffen=the evening coffee
aftenskole=evening school
aftensmad=dinner
agurker=cucumbers
al=all
aldrig=never
alene=alone
alle=all / everyone
alligevel=anyway / still
allé=avenue
alsidig=all-round / versatile
alt=everything / all
altan=balcony
altid=always
alvorlig=serious
anbefale=to recommend
anbefaler=recommend(s)
anden=other / second
andet=other / else
andre=others / other
angående=regarding
annonce=advertisement
annoncen=the advertisement
ansat=employed / an employee
ansatte=employees
ansøge=to apply
ansøgning=application
antallet=the number
app=app
appen=the app
arbejde=work / to work
arbejdede=worked
arbejder=works / is working
arbejdes=is worked
arbejdet=the work
arbejdsopgaver=work tasks
arbejdspladser=workplaces
arbejdspladserne=the workplaces
arbejdstider=working hours
arrangementer=events
arsenalet=the arsenal / the range
at=to / that
attraktiv=attractive
avis=newspaper
avisartikel=newspaper article
baby=baby
bad=bath / shower
badekar=bathtub
baderum=bathroom / washroom
badestrand=bathing beach
badeværelse=bathroom
badeværelser=bathrooms
badge=badge
badges=badges
bag=behind
bagefter=afterwards
bager=baker / bakery
bageri=bakery
bagerier=bakeries
bageriet=the bakery
bagud=behind
baguettes=baguettes
balance=balance
balanceøvelser=balance exercises
baller=buttocks
bange=afraid
bare=just / only
barnevogn=pram / baby carriage
baseret=based
beboere=residents
beboerne=the residents
bedre=better
bedst=best
bedste=best
bedt=asked
bedøm=assess / grade
bedømmer=assessor / grader
bedømmerarket=the assessment sheet
begge=both
begrund=give reasons for
begynder=begins / beginner
begyndere=beginners
begyndte=began
beklage=to apologise / to regret
beklager=apologise / regret
beliggende=located
beliggenheden=the location
beregn=calculate
beskriv=describe
beskrive=to describe
beslutter=decide(s)
besluttet=decided
bestemme=to decide
bestil=book / order
bestille=to book / to order
bestilte=ordered
består=consists
besøg=visit
besøge=to visit
besøger=visit(s)
besøgt=visited
betale=to pay
betragter=look at / watch
betyder=means
bevæge=to move
bevægelighed=mobility
bevægeligheden=the mobility
bevægelser=movements
bibliotek=library
biblioteket=the library
bil=car
bilen=the car
biler=cars
bilister=motorists
billig=cheap
billigere=cheaper
bindeord=connecting words / conjunctions
biografer=cinemas
bl=among others (bl.a.)
blad=magazine / leaf
bland-selv-koncept=pick-and-mix concept
bland-selv-slik=pick-and-mix sweets
blande=to mix
blander=mix(es)
blandt=among
blev=became / was
blevet=become / been
bliv=stay / become
blive=to become / to stay
bliver=becomes / is
blok=block
blot=just / only
bløde=soft
bo=to live
boblernes=the bubbles'
boede=lived
bogstav=letter (of the alphabet)
bogstav-svar=letter answer
bogstaver=letters
bogstavet=the letter
bolde=balls
bolig=home / housing
boligen=the home
boliger=homes
boligforening=housing association
boligforeningen=the housing association
boller=bread rolls
bollerne=the bread rolls
bor=live(s)
bordet=the table
borgmester=mayor
bosætter=settle
brev=letter
brombærsnitterne=the blackberry slices
brug=use / need
bruge=to use
bruger=use(s) / spend(s)
brugt=used / second-hand
brugte=used
bruseniche=shower cubicle
bruser=shower
bryggers=utility room
brænder=burn(s)
brød=bread
brødet=the bread
bus=bus
busforbindelser=bus connections
busserne=the buses
butik=shop
butikken=the shop
butikkens=the shop's
butiksmedarbejder=shop assistant
by=town / city
byde=to offer
byder=offers
byen=the town
byens=the town's
bygade=village street
bygget=built
bygning=building
både=both
bøjning=inflection
børn=children
børneafdeling=children's section
børnehave=kindergarten
børnehaven=the kindergarten
børnene=the children
børnevenligt=child-friendly
børneværelser=children's rooms
ca=approximately
cafeer=cafés
carport=carport
censor=external examiner
centralt=centrally
centrum=city centre
champagner=champagnes
charme=charm
charmerende=charming
chauffør=driver
chokoladeskærekagen=the chocolate cake
cirka=approximately
combo=combo
combo-bonus=combo bonus
computer=computer
computeren=the computer
coronapandemien=the corona pandemic
cpr-nummer=civil registration number
cykel=bicycle
cykelstier=bicycle paths
cykle=to cycle
cyklen=the bicycle
cyklende=cycling
cykler=cycle(s) / bicycles
da=when / since / then
dag=day
dage=days
dagen=the day
dagene=the days
dagens=today's / the day's
dagstur=day trip
danmark=Denmark
danmarks=Denmark's
danse=to dance
danseaerobic=dance aerobics
dansemotion=dance exercise
dansetrin=dance steps
dansk=Danish
danske=Danish
danskekspert=Danish expert
danskere=Danes
danskerne=the Danes
datingside=dating site
datingsiden=the dating site
dato=date
datoen=the date
datter=daughter
de=they / the
debatindlæg=opinion piece
december=December
dejlig=lovely
dejlige=lovely
dejligt=lovely
del=part
dele=parts / to share
deler=shares
deli=deli
delprøve=sub-test / exam part
deltage=to take part
deltager=take(s) part / participant
delvis=partly
delvist=partly
dem=them
den=it / the / that
denne=this
der=there / who / that
derefter=after that
deres=their
derfor=therefore
derhen=there (to that place)
derhjemme=at home
derimod=on the other hand / however
dertil=in addition
derudover=in addition
desuden=furthermore
desværre=unfortunately
det=it / the / that
dette=this
dialog=dialogue
dig=you
din=your
dine=your
direkte=direct(ly)
disken=the counter
diskursiv=discursive (how the text hangs together)
disponible=available / spare
dit=your
dk=.dk (Danish web address)
dobbelt=double
dog=however
drejer=is about (det drejer sig om = it's about)
drikker=drink(s)
dronningens=the queen's
drømmejob=dream job
drømmer=dream(s)
drømmested=dream place
du=you
durumbrød=durum bread
dybdeafspænding=deep relaxation
dyre=expensive
dyrere=more expensive
dyrkede=grew (plants)
dyrker=do / play (a sport)
dyrt=expensive
dørene=the doors
døtre=daughters
eddike=vinegar
efter=after
eftermiddag=afternoon
eftermiddagen=the afternoon
eftertragtet=sought-after
egen=own
eget=own
egne=own
ejendommen=the property
eksaminator=examiner
eksempel=example
eksempler=examples
eksemplet=the example
eksperter=experts
eksperterne=the experts
ekstra=extra
elastikker=elastic bands
elegant=elegant
elektriker=electrician
eleverne=the pupils
eller=or
ellers=otherwise
elsker=love(s)
emne=topic
emnet=the topic
en=a / an / one
end=than
ende=end
endelig=finally
endnu=yet / still
engelsk=English
enig=agree(d)
enige=agreed
enkelte=individual
enkeltes=the individual's
ens=one's / same
ensom=lonely
entreen=the hallway
entré=entrance hall
er=is / are
erfaring=experience
erfaringer=experiences
erne=(the …s, as in 1950'erne = the 1950s)
et=a / an / one
etplansvilla=single-storey house
europa=Europe
europæiske=European
fabrikker=factories
faciliteter=facilities
faktisk=actually
faktuelle=factual
familie=family
familien=the family
familier=families
familiestørrelse=family size
fantastisk=fantastic
fast=permanent / fixed
faste=fixed
fastfood=fast food
februar=February
feedback=feedback
fejlene=the mistakes
fejlfri=flawless
fejre=to celebrate
fejrer=celebrate(s)
fem=five
ferie=holiday
fest=party
festen=the party
fester=parties
festlokale=party room
filial=branch
find=find
finde=to find
finder=find(s)
fin=fine / nice
fine=fine / nice
fint=fine
fire=four
firma=company
firmaet=the company
fitnessrum=fitness room
fjerne=to remove
flere=more / several
flertal=plural
fleste=most
flisebelagt=tiled / paved
fliseterrasse=paved patio
flot=nice / impressive
flotte=nice / impressive
flytte=to move
flytter=move(s)
flyttet=moved
flæng=(i flæng = at random)
fokus=focus
for=for / because / too
forbedre=to improve
forbered=prepare
forberede=to prepare
forberedelse=preparation
forbindelse=connection
fordel=advantage
fordele=advantages
fordelene=the advantages
fordi=because
forebygge=to prevent
forelskede=in love
forelsket=in love
foreslå=to suggest
foreslår=suggest(s)
forhånd=(på forhånd = in advance)
forkert=wrong / false
forklar=explain
formål=purpose
forny=to renew
forside=front page
forsiden=the front page
forskellen=the difference
forskellige=different
forstå=to understand
forsøg=attempt
fortiden=the past
fortrinligt=excellent
fortræffelige=excellent
fortsætte=to continue
fortæl=tell
fortælle=to tell
fortællende=narrative
fortæller=tell(s)
foruden=besides
forventes=is expected
foråret=the spring
forårsløg=spring onions
forældre=parents
forældrene=the parents
forældresoveværelse=master bedroom
foto=photo
fotos=photos
fra=from
fransk=French
franske=French
fred=peace
fredag=Friday
fredelige=peaceful
fredeligt=peaceful
frem=forward / ahead
fremgang=progress
fremmest=(først og fremmest = first and foremost)
fremskridt=progress
fremstilling=composition / writing
fremstår=appears
fremtiden=the future
fri=free / off work
frihed=freedom
frikadeller=Danish meatballs
frisk=fresh
friskbagte=freshly baked
frisklavede=freshly made
frit=freely
fritid=free time
frivillige=volunteers
frokost=lunch
frokostpausen=the lunch break
fulgt=followed
fundet=found
fx=for example (e.g.)
fyldte=filled / turned (age)
fyr=guy
fyrværkeri=fireworks
fysioterapeut=physiotherapist
få=get / few
fået=got / received
får=get(s)
fås=is available
fælles=common / shared
fællesspisning=communal dining
færdig=finished
færdighed=skill
fødselsdag=birthday
fødselsdage=birthdays
føle=to feel
følelse=feeling
følg=follow
følge=to follow
før=before
føre=to lead / to carry on
først=first
første=first
førstegangskøbere=first-time buyers
førstesal=first floor (upstairs)
førstesalen=the first floor
gade=street
gammel=old
gang=time / walk / hallway
gange=times
gangen=the hallway
gardiner=curtains
gav=gave
gave=gift
gemt=saved
gengæld=(til gengæld = on the other hand)
gennem=through
gennemarbejder=works through
genoptræne=to rehabilitate
genskabt=recreated
gerne=gladly / would like to
gift=married
giftes=get married
gik=went
give=to give
giver=gives
gives=is given
glad=happy
glade=happy
gladere=happier
gluten=gluten
glutenfrie=gluten-free
glutenfrit=gluten-free
god=good
gode=good
godt=good / well
gourmetbagere=gourmet bakers
gratis=free (of charge)
grillbarer=snack bars
groft=rough
grund=plot of land / reason
grundig=thorough
grundige=thorough
grundlæggende=basic
græsplæne=lawn
gule=yellow
gulerodskagen=the carrot cake
gulvvarme=underfloor heating
gå=to walk / to go
gåafstand=walking distance
gået=gone / walked
går=go(es) / walk(s)
gælder=applies
gæstebadeværelse=guest bathroom
gæstetoilet=guest toilet
gør=do(es) / make(s)
gøre=to do / to make
haft=had
halvanden=one and a half
ham=him
han=he
handelsby=market town
handler=is about / shop(s)
hans=his
har=has / have
havde=had
have=garden / to have
haven=the garden
havnen=the harbour
hedder=is called
hej=hi
heldig=lucky
heldigvis=fortunately
hele=whole / all
heller=either (heller ikke = not either)
hellere=rather
helst=preferably
helt=completely
hen=(to a place)
hende=her
hendes=her
hente=to pick up
henvisninger=references
her=here
herefter=after this
hertil=in addition to this
herunder=including
hilsen=greeting / regards
hilsner=greetings / regards
hinanden=each other
hindbærsnitter=raspberry slices
historie=history / story
hits=hits
hjalp=helped
hjem=home
hjemland=home country
hjemme=at home
hjemmearbejde=working from home
hjemmebesøg=home visit
hjemmefra=from home
hjemmet=the home
hjul=wheels
hjælpe=to help
hjælpemidler=aids (allowed materials)
hjælpen=the help
hmm=hmm
hobby=hobby
hobbyer=hobbies
hold=team / class
holde=to hold / to keep
holder=hold(s) / keep(s)
holdet=the class / the team
holdningstekst=opinion text
holdt=held / kept
hos=at (someone's place)
huller=gaps / holes
hullerne=the gaps
hullet=the gap
hun=she
hund=dog
hunde=dogs
hurtig=quick
hurtigere=faster
hurtigt=quickly
hus=house
huset=the house
husets=the house's
husk=remember
husleje=rent
hvad=what
hvem=who
hver=each / every
hverdag=weekday / everyday life
hverdage=weekdays
hverdagen=everyday life
hverdagslivet=everyday life
hvert=each / every
hvide=white
hvidløg=garlic
hvilke=which
hvilken=which
hvilket=which
hvis=if
hvor=where / how
hvordan=how
hvorfor=why
hvorfra=from where
hvornår=when
hyggelig=cosy / nice
hyggelige=cosy / nice
hyggeligt=cosy / nice
hygger=have a nice time
håber=hope(s)
håndpillede=hand-peeled
håndvægte=hand weights
håndværker=craftsman
håndværkerne=the workmen
hænger=hang(s)
hæver=rise(s)
hævet=raised
høj=high / loud
høje=high
hør=listen / hear
høre=to hear / to listen
hører=hear(s) / belong(s)
i=in / you (plural)
idrætshal=sports hall
idé=idea
ifølge=according to
igen=again
igennem=through
ikke=not
ind=in / into
indbyggede=built-in
indehaverne=the owners
indeholder=contains
inden=before
indflytningsklar=ready to move into
indføring=introduction
indført=introduced
indholdet=the content
indkøb=shopping
indkøbsmuligheder=shopping facilities
indledning=introduction
indlæg=article / contribution
indre=inner
indretning=interior design / layout
indrettede=furnished / decorated
indsætte=to insert
influenza=flu
info=info
information=information
informationen=the information
informationer=information
informationstekst=information text
ingen=no / none / nobody
ingeniør=engineer
inspireret=inspired
institutioner=institutions (nurseries etc.)
instruktionen=the instructions
intens=intense
interessant=interesting
internettet=the internet
interview=interview
interviewet=the interview
inversion=inversion (verb before subject)
invitationen=the invitation
inviteret=invited
irritere=to annoy
især=especially
it-konsulent=IT consultant
italienske=Italian
ja=yes
jakke=jacket
jakken=the jacket
jeg=I
jer=you (plural)
jeres=your (plural)
jo=you know / after all
job=job
jobansøgning=job application
jobbet=the job
jul=Christmas
julefrokost=Christmas lunch
jævnligt=regularly
kaffe=coffee
kaffebrød=coffee cakes
kaffemaskine=coffee machine
kager=cakes
kalorier=calories
kampen=the fight
kan=can
kanelsnegle=cinnamon rolls
kanelting=cinnamon pastries
karakter=grade
kassen=the till / checkout
kedeligt=boring
kende=to know
kender=know(s)
kendt=known
kendte=knew
kigge=to look
kigger=look(s)
kilde=source
kip=ridge (roof)
kl=o'clock (kl. = time)
kladde=draft
klage=complaint / to complain
klager=complain(s)
klar=ready / clear
klaret=done / managed
klasse=class / grade
klasser=classes
klassiske=classic
klik=click
klinker=tiles
knasende=crunchy
kogehalvø=kitchen peninsula
kohærens=coherence
kohæsion=cohesion
kokossnitter=coconut slices
koldt=cold
kollega=colleague
kolleger=colleagues
kollegerne=the colleagues
kollegiet=the student residence
kollegium=student residence
kom=came / come
kombinerede=combined
komme=to come
kommer=come(s)
kommune=municipality
kommunen=the municipality
komparativ=comparative
koncentrere=to concentrate
kondition=fitness
konditionen=the fitness
konditionstræning=cardio training
kone=wife
kongens=the king's
konsistensen=the texture
kontakt=contact
kontakte=to contact
kontant=cash price
kontor=office
kontoransatte=office workers
kontoret=the office
koordinationen=the coordination
kop=cup
kort=short / card / map
korte=short
koster=costs
kr=kroner (DKK)
kransekage=marzipan ring cake
kredsløbet=the circulation
kredsløbstræning=circuit training
kriterier=criteria
kriterierne=the criteria
kroner=kroner (Danish currency)
krop=body
kroppen=the body
kroppens=the body's
krops=body's
kropsbevidsthed=body awareness
kropsbevidstheden=the body awareness
kræver=require(s)
kun=only
kunder=customers
kunderne=the customers
kunne=could
kunsten=the art / the trick
kvalitet=quality
kvarter=neighbourhood / quarter of an hour
kvinde=woman
kvindehold=women's class
kvinden=the woman
kvinder=women
kvittering=receipt
kælder=basement
kælderen=the basement
kære=dear
kæreste=boyfriend / girlfriend
kærlighed=love
kærligheden=love
køb=buy / purchase
købe=to buy
køber=buy(s) / buyer
købet=the purchase
købmandsbutik=grocery shop
købt=bought
køge=Køge (town)
køges=Køge's
køkken=kitchen
køkken-alrum=kitchen-family room
køkkenbordet=the kitchen table
køkkenet=the kitchen
køleskab=fridge
køre=to drive
kørekort=driving licence
kører=drive(s)
kørsel=driving
kørt=driven
kørte=drove
lade=let
land=country / countryside
lande=countries
landet=the country / the countryside
landligt=rural
landsby=village
landsbyen=the village
lange=long
langs=along
langt=far / long
larm=noise
lastbil=lorry / truck
lastbilchauffør=lorry driver
latinamerikanske=Latin American
latinerkvarteret=the Latin Quarter
lav=make / low
lave=to make / to do
lavede=made / did
laver=make(s) / do(es)
laves=be made
lavet=made
led=joints
ledes=is led
ledet=led
ledsætninger=subordinate clauses
lege=to play
legende=legend
legevenlig=good for playing
lejlighed=apartment
lejligheder=apartments
lejlighederne=the apartments
lektiehjælp=homework help
lektier=homework
let=easy / light
lette=easy
leve=to live
lide=(kan lide = like)
lidt=a little
lige=just / straight / equal
ligesom=like / just as
ligger=lies / is located
ligner=resemble(s)
lille=small
lingvistisk=linguistic
linje=line
linjen=the line
live-feedback=live feedback
live-tekst=live text
liv=life
livstruende=life-threatening
loft=ceiling
loftsrum=attic room
lokalerne=the premises
lov=permission / law
luft=air
lukkes=be closed
lukket=closed
lyder=sounds
lynlåsen=the zip
lys=light / bright
lyse=light / bright
lyset=the light
lyst=bright / desire
lytter=listening
lår=thighs
lås=unlock (lås op)
læben=the lip
læge=doctor
lægehuset=the doctor's surgery
lægen=the doctor
lægevagten=the out-of-hours doctor service
lækkert=delicious / lovely
længe=long (time)
længere=longer
lær=learn
lære=to learn / to teach
lærer=teacher
læreruddannede=trained as a teacher
lært=learned
læs=read
læse=to read
læseforståelse=reading comprehension
læsehest=bookworm
læseopgaver=reading tasks
læsning=reading
læsser=load(s)
løb=run
løbe=to run
løbeklub=running club
løber=run(s)
lørdag=Saturday
løsne=to loosen
mad=food
maden=the food
madvaner=eating habits
mail=email
mailet=emailed
mails=emails
maj-juni=May–June
man=one / you (people in general)
mand=man / husband
mandag=Monday
mange=many
manglede=was missing / lacked
mangler=is missing / lacks
marengskager=meringue cakes
marker=fields
marmelade=jam
marts=March
masser=lots
match=match
matematik=mathematics
mave=stomach
mavebøjninger=sit-ups
med=with
medarbejderne=the employees
medborgerhuset=the community centre
medlemmer=members
meget=very / much
mellem=between
meltyper=types of flour
men=but
mener=think / mean
mening=opinion / meaning
mennesker=people
mens=while
mere=more
mest=most
meste=most
midt=in the middle
midtbybageren=the city-centre baker
midte=middle
mig=me
mikrofonen=the microphone
miljøvenlig=environmentally friendly
millioner=millions
min=my
mindre=smaller / less
mindst=at least
mine=my
minikager=mini cakes
minimum=minimum
minutter=minutes
minutters=minutes'
mit=my
mod=towards / against
modeller=models
modelsvar=model answer
modelsvaret=the model answer
modtageren=the recipient
monolog=monologue
mor=mother
morfologi=morphology (word endings)
morgen=morning
morgenen=the morning
morgenmad=breakfast
motion=exercise
motionsgymnastik=fitness gymnastics
motionshold=exercise classes
motorvejen=the motorway
muffins=muffins
mulighed=possibility / option
muligheder=possibilities / options
muligt=possible
mundtlig=oral
muret=bricked
musik=music
muskel=muscle
muskelgrupper=muscle groups
muskler=muscles
musklerne=the muscles
muskulaturen=the muscles
mål=goal / target
målet=the goal
målrettet=aimed at
måned=month
måneden=the month
måneder=months
mænd=men
mærke=to feel / to notice
møde=to meet / meeting
mødes=meet
mørke=dark
müsliboller=muesli rolls
nabo=neighbour
naboer=neighbours
naboerne=the neighbours
nabolaget=the neighbourhood
nakke=neck
natten=the night
naturen=nature
navn=name
navnet=the name
ned=down
nej=no
nemlig=you see / namely
nervøse=nervous
nettet=the net / the internet
niv=level (abbr.)
niveau=level
niveauer=levels
nogen=someone / any
noget=something / some
nogle=some
nok=enough / probably
normalt=normally
november=November
nr=no. (number)
nu=now
nulstil=reset
ny=new
nybegynder=beginner
nyder=enjoy(s)
nydes=be enjoyed
nye=new
nyeste=newest
nymalede=newly painted
nyt=new
nyttige=useful
nytår=New Year
nå=well / reach
når=when / reach(es)
nærheden=the vicinity
næste=next
næsten=almost
nævner=mention(s)
nødt=(være nødt til = have to)
nødvendigt=necessary
nøgle=key
nøglen=the key
nøjagtigt=exactly
offentlig=public
officielle=official
ofte=often
og=and
også=also
okay=okay
oksebryst=beef brisket
om=about / if / around
omgivelser=surroundings
områder=areas
ondt=pain (have ondt = be in pain)
onsdag=Wednesday
onsdagen=Wednesday
op=up
opbygge=to build up
opdagede=discovered
opfølgende=follow-up
opført=built
opgave=task
opgaverne=the tasks
opholdsafdeling=living area
opholdsstue=living room
opkaldt=named
oplagt=obvious
oprindelig=originally
opslag=notice / post
optage=to record
optagelse=recording
optagelsen=the recording
optimale=optimal
opvarmning=warm-up
ord=word(s)
ordantal=word count
ordantallene=the word counts
ordentligt=properly
ordjagt=word hunt
ordjæger=word hunter
ordklassen=the word class
ordre=order
ordrenummeret=the order number
ordsamler=word collector
ordsmed=wordsmith
ordstilling=word order
ordvalg=choice of words
organisering=organisation
os=us
ost=cheese
over=over / about
overdækket=covered
pakken=the parcel
panden=the forehead
par=couple / pair / a few
parat=ready
parken=the park
parkering=parking
parkeringsplads=car park
parret=the couple
passende=suitable
passer=fits / suits / looks after
penge=money
pengene=the money
pensionister=pensioners
perfekt=perfect
persisk=Persian
person=person
pige=girl
plads=space / place
plan=floor / level / plan
planlæg=plan
planlægge=to plan
planter=plants
pludselig=suddenly
point=points
pointene=the points
pragmatisk=pragmatic (does the text do its job?)
primært=primarily
pris=price
priser=prices / awards
problem=problem
problemer=problems
problemet=the problem
procent=percent
produkter=products
profil=profile
profiler=profiles
projektet=the project
præcise=precise
præsenter=introduce
præstation=performance
prøv=try
prøve=test / exam / to try
prøvede=tried
prøven=the test / the exam
prøver=tests / tries
prøvesæt=exam set
prøvesættet=the exam set
pulsen=the pulse
punkter=points
punktum=full stop
på=on / at
pæn=nice / neat
pænt=nicely / neat
rabat=discount
radioen=the radio
ramme=box / frame
rammer=frames / setting
rask=healthy / well
recept=prescription
redskaber=equipment
referenceramme=frame of reference
regler=rules
regner=rains / calculate
regnes=is calculated
rejer=prawns
rejse=to travel / journey
rejser=travel(s) / journeys
rekord=record
renovere=to renovate
rent=clean
reparation=repair (how easy the text is to understand)
repetition=repetition
replik=line (in a dialogue)
replikker=lines (in a dialogue)
restaurant=restaurant
ret=dish / right / quite
retorisk=rhetorical
retskrivning=spelling
rettenøgle=answer key
rigtig=right / really
rigtige=right / correct
rigtigt=right / true
rimer=rhymes
ring=call
ringe=to call / poor
ringer=call(s)
ristet=toasted
ro=peace / calm
rolige=quiet / calm
roligt=calm
rugbrød=rye bread
rulninger=rolls (exercise)
rum=rooms / room
rummelige=spacious
rummer=contains
rundt=around
rydder=tidies (rydde op = tidy up)
ryg=back
ryggen=the back
råd=advice / afford (have råd til)
rækker=rows
rød=red
røget=smoked
sager=things
sal=floor / hall
salg=sale
salsa=salsa
samarbejde=to cooperate
samarbejder=cooperate(s)
samba=samba
saml=collect
samlet=gathered / total
samme=same
sammen=together
sammenhængende=coherent
sammenlign=compare
samt=and / as well as
samtale=conversation
samtalen=the conversation
samtalepartner=conversation partner
sandwiches=sandwiches
savne=to miss
savner=miss(es)
scones=scones
se=see / look
sekretær=secretary
seks=six
sekunder=seconds
selv=self / even
selvfølgelig=of course
selvom=even though
sende=to send
sender=send(s)
senest=at the latest
seneste=latest
seng=bed
ser=see(s) / look(s)
ses=see each other
sidde=to sit
sidder=sit(s)
side=side / page
siden=since / the page
sidst=last
sidste=last
sig=himself / herself / themselves
sige=to say
siger=say(s)
signaler=signals
sikker=sure / safe
sikre=to ensure / safe
sin=his / her / its (own)
sind=mind
sine=his / her (own)
single=single
singler=singles
sit=his / her (own)
sjov=fun
sjovt=fun
skabe=cupboards / to create
skabes=is created
skader=injuries
skal=must / shall / will
skarpt=sharp (skyde med skarpt = go all out)
skidt=bad
skole=school
skoleelever=schoolchildren
skoleleder=head teacher
skolen=the school
skoler=schools
skov=forest
skoven=the forest
skriftlig=written
skriftlige=written
skriv=write
skrive=to write
skrivecoach=writing coach
skrivecoachen=the writing coach
skrivekarl=writer
skriveopgaven=the writing task
skriveopgaver=writing tasks
skriver=write(s)
skrivning=writing
skrue=turn (skrue ned = turn down)
skud=shot (skud på stammen = new addition)
skuffet=disappointed
skuldre=shoulders
skulle=should / was going to
skyder=shoot(s)
skærekager=sliced cakes
skøn=lovely / estimate
skønne=lovely
skønt=lovely
slet=at all (slet ikke = not at all)
slette=to delete
slog=struck (slog dørene op = opened)
slut=end / over
slutter=ends
smage=to taste
smagen=the taste
smagt=tasted
smidig=supple
smidighed=flexibility
smil=smile
smukke=beautiful
små=small
småkagefronten=the biscuit front
småkagehuset=the cookie house (bakery name)
småkager=biscuits / cookies
småreparationer=small repairs
snakke=to chat
snakkemester=chat master
snakker=chat(s)
snegle=cinnamon swirls
sofahygge=cosy time on the sofa
solen=the sun
solrig=sunny
solrige=sunny
som=as / like / who / that
somme=(somme tider = sometimes)
sommer=summer
sort=black
sortfodsskinke=Iberian ham
sortiment=range
sove=to sleep
soveværelser=bedrooms
spansk=Spanish
sparer=save(s)
specialbrød=speciality bread
spelt=spelt
spidsen=the head / the top
spil=play / game
spise=to eat
spiseplads=dining area
spiser=eat(s)
spisestue=dining room
spisning=eating / dining
sport=sport
spring=skip (spring over)
sprogcafé=language café
sprogcenter=language centre
sprogskole=language school
sprogskolen=the language school
sprogskolens=the language school's
sprængt=salt-cured
spændende=exciting
spændinger=tensions
spørg=ask
spørger=ask(s)
spørgsmål=question(s)
spørgsmålene=the questions
spørgsmålet=the question
squats=squats
stadig=still
stammen=the trunk (skud på stammen = new addition)
stand=condition
start=start
starte=to start
starter=start(s)
startes=be started
startet=started
staten=the state
stationen=the station
stavning=spelling
sted=place
steder=places
stedet=the place
steget=risen
stenovnsbagte=stone-oven baked
stikord=keywords / notes
stil=style
stille=quiet / to put
stiller=put(s) / place(s)
stop=stop
stoppe=to stop
stopper=stops
stor=big
storbyens=the big city's
store=big
stort=big
straks=immediately
strammet=tightened / toned
strand=beach
stranden=the beach
stress=stress
stribe=strip / series
struktur=structure
stræk=stretches
strømmer=streams
studenterbrød=student bread (cake)
studerer=study / studies
stue=living room
stueetagen=the ground floor
stuen=the living room
stueplan=ground floor
stueplanets=the ground floor's
stuer=living rooms
stykker=pieces (i stykker = broken)
styrke=strength / to strengthen
styrket=strengthened
stået=stood
står=stand(s) / is written
stærk=strong
større=bigger
størrelse=size
største=biggest
støv=dust
succes=success
suite=(en suite = connected rooms)
sund=healthy
sundhed=health
sundhedskort=health insurance card
sundhedskortet=the health insurance card
sundhedssystem=health system
sundt=healthy
supermarkedet=the supermarket
sur=angry / sour
surdej=sourdough
svag=weak
svar=answer
svarer=answer(s)
svaret=the answer
sved=sweat
sværere=harder
svært=difficult
svømme=to swim
svømmehal=swimming pool
svømmehold=swimming class
sydvendt=south-facing
syg=ill / sick
sygdom=illness
synes=think / feel
synspunkter=points of view
syntaks=syntax (sentence structure)
syv=seven
så=so / then / saw
sådan=like that / such
såkaldte=so-called
sælgeren=the seller
sælges=for sale
særdeles=extremely
særskilt=separate
sætning=sentence
sætningen=the sentence
sætninger=sentences
sætningsbygger=sentence builder
sætningslængde=sentence length
sætningsstarter=sentence openings
sætter=put(s) / set(s)
sød=sweet / nice
søde=sweet
søge=to apply / to search
søger=seek(s) / looking for
søn=son
søndag=Sunday
sørger=make(s) sure
tag=roof / take
tage=to take
tager=take(s)
taget=taken / the roof
tagterrasse=roof terrace
tak=thanks
tal=speak / number
tale=speaking / to speak / speech
taleopgaver=speaking tasks
taletid=speaking time
taletiden=the speaking time
taleøvelserne=the speaking exercises
talt=spoken
talte=spoke
tanken=the petrol station / the thought
tankstationer=petrol stations
tebirkes=poppy-seed pastries
tegnsætning=punctuation
tekst=text
teksten=the text
tekster=texts
teksterne=the texts
telefonen=the phone
telefonnummeret=the phone number
tema=theme
tempo=pace
terrasse=terrace / patio
terrassemiljø=patio area
terrasser=terraces
tester=tests
tid=time
tiden=the time
tider=times
tidernes=(i tidernes løb = over time)
tidligere=earlier / previously
tidligt=early
til=to / for
tilbage=back
tilbud=offers / facilities
tilfreds=satisfied
tilfredse=satisfied
tilfældigt=random
tillader=allows
tilmelde=to sign up
tilmelding=registration
tilpasser=adapts
tilrettet=adapted
time=hour / lesson
timen=the lesson / the hour
timer=hours / timer
ting=things
tip=tip
tirsdage=Tuesdays
tit=often
tjek=check
tjener=earn(s)
tlf=phone (tlf.)
to=two
tog=train / took
toget=the train
togstationen=the train station
toilet=toilet
tomat=tomato
tomater=tomatoes
tonen=the tone
torsdag=Thursday
torv=square (town square)
tradition=tradition
traditioner=traditions
traditionsrige=traditional
trafik=traffic
transport=transport
transportfirma=transport company
trappe=stairs
tre=three
tredje=third
trinene=the steps
trins-skalaen=(7-trins-skalaen = the 7-point grading scale)
tror=think / believe
trygt=safe
tryk=press
tråd=thread (rød tråd = common thread)
træk=draw / pull (i træk = in a row)
trække=to pull / to go out
træn=train / practise
træne=to train / to exercise
træner=train(s) / trainer
trænet=trained
træning=training
træningen=the training
træt=tired
træterrasse=wooden terrace
tunesiske=Tunisian
tur=trip / walk
turde=dared
ture=trips
tusind=thousand
tv=TV
tydeligt=clearly
type=type
typer=types
tyskland=Germany
tærter=tarts
tæt=close
tøj=clothes
tømrer=carpenter
ud=out
udbydes=is offered
uddannelse=education
uddrag=extract
ude=out / outside
udekøkken=outdoor kitchen
udelivet=outdoor life
uden=without
udestue=conservatory
udestuen=the conservatory
udflugt=trip / excursion
udfolde=to unfold
udfordrende=challenging
udfordringer=challenges
udfyld=fill in
udfyld-hullerne=fill in the gaps
udgang=exit / access
udhus=shed
udlandet=abroad
udover=besides
udsigt=view
udstræk=stretching
udstrækning=stretching
udstyr=equipment
udtrykke=to express
udvalg=selection
udvalget=the selection
uge=week
ugen=the week
uger=weeks
ulejligheden=the inconvenience
ulempe=disadvantage
ulemper=disadvantages
ulykke=accident
ulykker=accidents
under=under / during
undersøge=to investigate
undersøgelse=study / survey
undervisningen=the lessons / teaching
unge=young people
ungt=young
universitet=university
usundt=unhealthy
utilfreds=dissatisfied
vafler=waffles
var=was / were
varer=goods / lasts
varet=lasted
varianten=the variant
variation=variation
varierede=varied
varierer=varies
varme=warmth / heat
varmer=warm(s)
varmet=warmed
vaskemaskine=washing machine
vasker=wash(es)
vaskerum=laundry room
vaskesøjle=washer-dryer stack
ved=at / by / know(s)
vedligeholde=to maintain
vej=road / way
veje=roads / to weigh
vejene=the roads
vejledende=guiding / recommended
vejret=the weather
velholdt=well-maintained
velholdte=well-maintained
velkommen=welcome
velkomne=welcome
velvalgt=well-chosen
ven=friend
vendinger=phrases / expressions
venlig=kind
vennen=the friend
venner=friends
vente=to wait
verbernes=the verbs'
verbet=the verb
verden=the world
verdener=worlds
version=version
vest=west
vestjylland=West Jutland
vi=we
vide=to know
videre=on / further
vigtig=important
vigtigere=more important
vigtigt=important
vil=want(s) / will
villa=detached house
villaen=the house
ville=would / wanted
vinde=to win
vinduer=windows
vinduerne=the windows
vindueskarmene=the windowsills
vinduespartier=window sections
vinkelstue=L-shaped living room
vinterjakke=winter jacket
virker=works / seems
virksomheder=companies
viser=shows
voksne=adults
vores=our
vundet=won
vurdere=to assess
vurderer=assess(es)
vurdering=assessment
våde=wet (våde varer = drinks)
væk=away
vælg=choose
vælge=to choose
vælger=choose(s)
vær=be
værd=worth
være=to be
værelse=room
værelser=rooms
værelset=the room
været=been
værste=worst
webbutik=online shop
webbutikken=the online shop
weekenden=the weekend
yderligere=further / additional
ydervægge=outer walls
yngre=younger
yoga=yoga
yogastillinger=yoga poses
zumba=zumba
åben=open
åbent=open
åbne=open
åbnede=opened
år=year(s)
året=the year
årets=the year's
års=year's (40-års = 40th)
årsagen=the reason
ås=ridge
æble-kanel=apple-cinnamon
æbler=apples
ægteparret=the married couple
ægteparrets=the married couple's
ældste=oldest
ærlig=honest
én=one
øge=to increase
øges=is increased
øget=increased
ølandshvede=Øland wheat
ønsker=wish(es)
øv=practise
øve=to practise
øvede=practised / experienced
øvelser=exercises
øvelserne=the exercises
øvemål=practice target
øvet=practised
øvrige=other / remaining
aerobichold=aerobics class
folk=people
oktober=October
placering=placement / position
sfo=after-school club (SFO)
vane=habit
schweizerdeli=Swiss deli
comté-ost=Comté cheese
chilimayo=chilli mayo
mobilepay=MobilePay (Danish payment app)
københavn=Copenhagen
syrien=Syria
iran=Iran
odense=Odense (city)
esbjerg=Esbjerg (city)
vestby=Vestby (town)
streak=streak (days in a row)
xp=XP (experience points)
opgaver=tasks
løst=solved
holdningstekster=opinion texts
bedømmelse=assessment
bedømt=assessed
oplæsning=reading aloud
emner=topics
prøvetid=exam time
rammen=the box / the frame
set=seen
situationen=the situation
ad=along / down (ned ad = down)
pd=PD (Prøve i Dansk)
co=co. (and company)
www=www (web address)
ida=(a name)
frank=(a name)
anna=(a name)
tom=(a name)
toms=(a name)
jessen=(a name)
mette=(a name)
holm=(a name)
amir=(a name)
sofia=(a name)
jonas=(a name)
hansen=(a name)
leilas=(a name)
sara=(a name)
jensen=(a name)
peter=(a name)
ali=(a name)
maria=(a name)
lopez=(a name)
hanne=(a name)
tran=(a name)
ahmed=(a name)
karimi=(a name)
fatima=(a name)
berg=(a name)
jens=(a name)
lise=(a name)
nielsen=(a name)
maja=(a name)
karen=(a name)
husted=(a name)
christian=(a name)
funder=(a name)
tine=(a name)
lajer=(a name)
petersen=(a name)
lars=(a name)
karin=(a name)
lone=(a name)
klemmenstrupvej=(street name)
hasselvej=(street name)
kildevej=(street name)
ølbyvej=(street name)
langesvej=(street name)
vordingborgvej=(street name)
egevej=(street name)
stormøllevej=(street name)
smedevej=(street name)
køgevej=(street name)
lidemarksvej=(street name)
mejlgade=(street name)
åboulevarden=(street name)
graven=(street name)
ølby=(place name)
ulstrup=(place name)
lidemark=(place name)
valløskovene=(place name)
frederiksbjerg=(place name)
åbyhøj=(place name)
briancon=(business / website name)
schweizerbageriet=(business / website name)
tøjnet=(business / website name)
friskkøb=(business / website name)
jobindex=(business / website name)
boligvest=(business / website name)
smagaarhus=(business / website name)
nowruz=Nowruz (Persian New Year)
bruuns=(part of a street name)
frederiks=Frederik's (street name)
ak=AK (name of the evening school)
aerobic=aerobics
administration=administration
administrative=administrative
afdeling=department
afgifter=taxes / duties
afskaffer=abolish(es)
aften=evening
aktuelle=current
alder=age
aldersgrænse=age limit
allerede=already
almindelig=ordinary / normal
altanerne=the balconies
alternativt=alternative
alvorligt=seriously
ambitiøs=ambitious
analysere=to analyse
anderledes=different(ly)
anmode=to request (anmode om)
annoncer=advertisements
ansvar=responsibility
ansætte=to employ / to hire
ansøgninger=applications
apps=apps
arbejdsliv=working life
arbejdsmailen=the work email
arbejdsplads=workplace
arbejdspladsen=the workplace
arbejdstid=working hours
arbejdsuge=working week
argument=argument
argumentation=argumentation
argumenter=argue / arguments
argumentere=to argue
argumenterende=argumentative
argumenterer=argue(s)
artikel=article
artikler=articles
babysvømning=baby swimming
badede=bathed / swam
bageren=the baker's
baggrund=background
balancen=the balance
banket=knocked / hammered
barn=child
barnet=the child
barnets=the child's
beboer=resident
beboermøde=residents' meeting
begrunde=to justify / give reasons
begår=commit(s) / make(s) (mistakes)
beholde=to keep
bekymrede=worried
bekymring=concern / worry
beløb=amount
besked=message
beskeder=messages
besluttede=decided
bestyrelsen=the board
besvare=to answer
betyde=to mean
betydet=meant
bevæget=moved
bidrage=to contribute
billetsystemer=ticket systems
billigt=cheap(ly)
blå=blue
boet=lived
boligområder=residential areas
boligorganisation=housing organisation
bondehus=farmhouse
borde=tables
boret=drilled
breve=letters
brugen=the use
bruges=is used
budget=budget
budgettet=the budget
buskort=bus pass
busser=buses
byggeri=construction
byggeriet=the construction site
byrådet=the town council
bøger=books
bør=should / ought to
børns=children's
cafeerne=the cafés
cyklede=cycled
cykelværksted=bicycle repair shop
dannelse=education / formation (digital dannelse = digital literacy)
danskprøver=Danish tests
data=data
debat=debate
deltagelse=participation
deltaget=taken part
demokrati=democracy
demokratiet=democracy
dermed=thereby / thus
desto=(ikke desto mindre = nevertheless)
digital=digital
diskussion=discussion
diskuter=discuss
diskutere=to discuss
disse=these
droppet=dropped
drømte=dreamed
dyr=expensive / animal
dårligere=worse
dårligt=bad(ly)
dæk=tyre
dør=door
døren=the door
efterhånden=gradually
efterlyse=to call for
efterlyser=call(s) for
eftersom=since / as
efteruddannelse=further training
egenskab=quality / trait
egenskaber=qualities
ekspedient=shop assistant
ekstern=external
elev=pupil / student
elever=pupils
ender=end(s) up
ene=one (på den ene side = on the one hand)
enkel=simple
enkle=simple
erhverv=business / trade
etværelseslejlighed=one-room flat
fag=subject(s)
fagforeningerne=the trade unions
faglig=academic / professional
fagligt=academically
farlig=dangerous
farve=colour
farvel=goodbye
fat=hold (få fat i = get hold of)
fattige=poor
feber=fever
feedbacken=the feedback
fejl=mistake(s) / error(s)
festudvalget=the party committee
fik=got / received
film=film(s)
findes=exists / be found
firedages=four-day
fjerner=remove(s)
fladt=flat
fleksibel=flexible
flyrejser=air travel / flights
flyt=move
flytningen=the move
fodbold=football
fokusere=to focus
fokuserer=focus(es)
folkeskolen=the public school (primary and lower secondary)
forbruger=consumer
forbud=ban
forbyde=to ban
forbydes=be banned
foregår=takes place
forening=association / club
foreningen=the association
foreningslivet=club and association life
forestille=to imagine (forestille sig)
forhandl=negotiate
forhandle=to negotiate
forkerte=wrong
forklare=to explain
form=form / shape
formel=formal
formelle=formal
formiddag=morning (before noon)
fornavn=first name
fornuftigt=sensibly
forskel=difference
forskere=researchers
forskerne=the researchers
forskning=research
forskningslaboratorierne=the research laboratories
forslag=proposal / suggestion
forslaget=the proposal
forstyrrer=disturb(s)
forståelse=understanding
forstået=understood
forstår=understand(s)
forsvinder=disappear(s)
fortjener=deserve(s)
fortryde=to regret
fortryder=regret(s)
forvirring=confusion
forælder=parent
franskbrød=white bread
frikvarterer=breaks (at school)
frikvartererne=the breaks
frisør=hairdresser
frister=tempt(s)
fritidsaktiviteter=leisure activities
frivillig=volunteer / voluntary
fungerer=work(s) / function(s)
fylde=to fill
fyraften=end of the working day
fyret=fired
fysik=physics
fælde=to cut down (trees)
fællesskab=community / togetherness
færdigheder=skills
færdigt=finished
færre=fewer
føler=feel(s)
gaden=the street
galt=wrong (hvad er der galt = what's wrong)
gamle=old
gammelt=old
generalforsamlingen=the general meeting
giv=give
gjort=done / made
glemme=to forget
glemt=forgotten
glæder=look(s) forward (glæder sig)
grillen=the barbecue
griner=laugh(s)
grundlag=foundation / basis
grupper=groups
grå=grey
grænserne=the limits
grønne=green
gymnasielærer=upper-secondary school teacher
gymnasierne=the upper-secondary schools
gymnastikforening=gymnastics club
gården=the courtyard
gårdfest=courtyard party
gøres=be done
halsen=the throat
halv=half (halv ni = half past eight)
halvdelen=half
halvt=half
handle=to shop / to act
hav=have (hav en god dag = have a nice day)
hel=whole
henter=pick(s) up
henvende=to contact (henvende sig)
henvendelser=enquiries
henvender=contact / approach
henvis=refer
herfra=from here
hermed=hereby
herreklip=men's haircut
hjemmesiden=the website
hjælp=help
hjælper=help(s)
hk=HK (a trade union)
holdbarhed=shelf life / durability
holdbarhedsdatoerne=the best-before dates
holdning=opinion / attitude
holdninger=opinions
hovedstaden=the capital
hul=gap / hole
hundrede=hundred
hundredtusindvis=hundreds of thousands
huse=houses
huske=to remember
huslejen=the rent
hverdagsdansk=everyday Danish
hverdagsliv=everyday life
hverdagstekster=everyday texts
hvorefter=after which
hvorhen=where to
hvorimod=whereas
håndtere=to handle
hårdt=hard
hævde=to claim
højere=higher
højre=right (til højre = to the right)
hørt=heard
imellem=between
imidlertid=however
imod=against
indbyggere=inhabitants
inddrag=include / involve
inddrage=to involve
inddrager=involve(s)
inde=inside (låst inde = locked away)
indendørs=indoors
indhold=content
indkomst=income
integration=integration
integrationen=the integration
intelligens=intelligence (kunstig intelligens = AI)
interesse=interest
investerer=invest(s)
investering=investment
journalist=journalist
journalistik=journalism
jobportalen=the job portal
kage=cake
kalder=call(s)
kandidatgrad=master's degree
karakterer=grades / marks
karaktererne=the grades
karakterfri=without grades
kedelige=boring
kirken=the church
klagede=complained
klare=clear / to manage
klarer=manage(s) / cope(s)
klima=climate
klimaet=the climate
klimaets=the climate's
klimaproblemerne=the climate problems
klimavenlige=climate-friendly
klip=haircut / cut
knap=just under / barely
knus=hugs
kold=cold
kommet=come
kommunens=the municipality's
kommunikationsmedarbejder=communications officer
kommunikere=to communicate
kompromis=compromise
konkluderer=conclude(s)
konklusion=conclusion
konkret=concrete / specific
konkrete=concrete / specific
kontrol=control / checks
kontrollerer=check(s)
korrekte=correct
kostede=cost
kraftig=powerful / loud
krav=requirement / demand
kreativ=creative
kritikerne=the critics
krævede=required
kultur=culture
kundehenvendelser=customer enquiries
kundeservicemedarbejder=customer service worker
kunstig=artificial
kursus=course
kurven=the basket
kvadratmeter=square metres
kvaliteten=the quality
købte=bought
kød=meat
lad=let (lad os = let's)
lang=long
langsomt=slowly
larmen=the noise
larmer=make(s) noise
larmes=noise is made
ledelsen=the management
leder=manager / leader
legetøj=toys
lejligheden=the apartment
lettere=easier
ligeud=straight ahead
listen=the list
livet=life
livret=favourite dish
livsstil=lifestyle
lokal=local
lokalavis=local newspaper
lokale=local
lokalsamfund=local community
lokalsamfundet=the local community
lommen=the pocket
loppemarked=flea market
luftforurening=air pollution
låst=locked
lægger=put(s) / place(s) (lægge vægt på = emphasise)
lærere=teachers
læreren=the teacher
læring=learning
læringen=the learning
lærte=learned
læser=read(s) / reader
læserbrev=letter to the editor
læst=read
løn=salary / pay
lønforhøjelse=pay rise
lørdage=Saturdays
lørdags=(i lørdags = last Saturday)
løse=to solve
løses=be solved
løsning=solution
løsninger=solutions
madspild=food waste
malet=painted
mandag-fredag=Monday to Friday
maskiner=machines
maskinerne=the machines
medarbejdere=employees
medarbejdernes=the employees'
medier=media
medmindre=unless
mellemstor=medium-sized
menneske=human being / person
meter=metre(s)
miljø=environment
mindske=to reduce
mindste=smallest (i det mindste = at least)
mister=lose(s)
mobilfri=mobile-free
mobiltelefoner=mobile phones
modargument=counterargument
modsætning=contrast (i modsætning til = unlike)
mundtligt=orally
myldretiden=rush hour
myndigheder=authorities
må=may / must
måde=way
måler=measure(s)
måtte=had to / might
mængderabatter=bulk discounts
møder=meetings / meet(s)
mørkt=dark
nabobyen=the neighbouring town
nedenfor=below
nedsat=reduced
nemmeste=easiest
nervøs=nervous
ni=nine
nuværende=current
nyhedsbrev=newsletter
nyhedsbreve=newsletters
nysgerrig=curious
offentlige=public
omstilling=transition (grøn omstilling = green transition)
opdaterer=update(s)
opefter=upwards
opfinde=to invent / make up
opgangen=the stairwell
oplever=experience(s)
oplysninger=information
oplægsholder=speaker / presenter
opmærksomheden=the attention
opslagstavlen=the noticeboard
opstår=arise(s) / occur(s)
otte=eight
overbevist=convinced
overflødig=redundant / superfluous
overflødige=redundant
overrasket=surprised
overskredet=exceeded
overskride=to exceed
overskudsmad=surplus food
overveje=to consider
overvejer=consider(s)
paraply=umbrella
paraplyen=the umbrella
parkere=to park
parkeringspladser=parking spaces
passe=to look after / to fit
patienter=patients
peger=point(s) (pege på = point out)
pensionist=pensioner
personer=people / persons
personlige=personal
plejecenter=care home
plejehjem=nursing home
plus=plus
pointe=point
politiker=politician
politikerne=the politicians
pose=bag
presset=pressured
prisen=the price
programmør=programmer
præcist=precisely
prøverne=the exams
prøvet=tried
påvirker=affect(s)
rapport=report
rapporten=the report
rapporter=reports
redaktør=editor
reducere=to reduce
regeringen=the government
regne=to rain
regnede=rained
relevante=relevant
reparerer=repair(s)
restauranter=restaurants
resten=the rest
resultater=results
resultatet=the result
retfærdig=fair
retningslinje=guideline
retningslinjer=guidelines
rimelig=reasonable
rimeligt=reasonable
ringere=worse / poorer
risici=risks
rolle=role
rutineopgaver=routine tasks
rygning=smoking
sad=sat
saftevand=squash (fruit drink)
sagen=the matter / the case
samfund=society
samfundet=society
samfundsemner=social issues
sammenlignende=comparative
sammenligner=compare(s)
sammenlignet=compared
sammenligning=comparison
samtaler=conversations
samtidig=at the same time
selvstændighed=independence
selvstændigt=independently
sendt=sent
senere=later
september=September
sikkert=probably / safely
skab=cupboard / locker
skaber=create(s)
skabt=created
skinnede=shone
skolebørn=schoolchildren
skoledagen=the school day
skoleforsker=school researcher
skolegården=the schoolyard
skoletid=school hours
skoletiden=school hours
skraldespanden=the bin
skygger=shade(s)
skyld=sake (for … skyld = for the sake of)
skåret=sliced
skærm=screen
skærmen=the screen
skærmtid=screen time
slukke=to turn off
slukket=switched off
smartphone=smartphone
smartphones=smartphones
smider=throw(s) (smide ud = throw away)
sms=text message
snart=soon (så snart = as soon as)
sne=snow
sociale=social
sofa=sofa
sofaen=the sofa
spild=waste
spille=to play
spiller=play(s)
spiselig=edible
spiste=ate
sproget=the language
sprogkrav=language requirement
spørge=to ask
startede=started
starten=the start
statsborgerskab=citizenship
steg=rose
stemme=to vote / voice
stemmer=vote(s)
stillet=put / asked (stillet krav = made demands)
stilling=position (job)
stillingen=the position
stillinger=positions
stod=stood (stod op = got up)
stole=chairs
storby=big city
stramt=tight
strategi=strategy
stresset=stressed
struktureret=structured
studerende=student(s)
styre=to control / to steer
stå=stand
stærke=strong
støj=noise
størst=biggest
støtte=to support
støtter=support(s)
su=SU (Danish student grant)
succesfulde=successful
sukker=sugar
sundhedssystemet=the health system
sundhedsudfordring=health challenge
supermarkeder=supermarkets
supermarkedernes=the supermarkets'
svare=to answer
sværeste=hardest
syge=ill / sick
sygeplejerske=nurse
sygt=ill / sick
synspunkt=point of view
system=system
systemer=systems
systemerne=the systems
sælg=sell
sælge=to sell
sælger=sell(s) / seller
sænkes=be lowered
sætte=to put / to set
søgning=search
taler=speak(s) / speaker
talsperson=spokesperson
tand=tooth
tandlæge=dentist
tandlægen=the dentist
tandlægerne=the dentists
tankegange=ways of thinking
taske=bag
te=tea
teams=teams
teknik=technical services
teknologi=technology
teknologien=the technology
tekstsammenhæng=text coherence
telefon=phone
telefonerne=the phones
temadag=theme day
temadage=theme days
temadagen=the theme day
ti=ten
tidligst=at the earliest
tidsbestilling=appointment
tilbyder=offer(s)
timers=hours'
tobak=tobacco
tons=tonnes
trafikken=the traffic
trafikuheld=traffic accidents
trivsel=well-being
troværdig=credible
troværdige=credible
trygge=safe / secure
træer=trees
træerne=the trees
trætte=tired
tvivle=to doubt
typisk=typical(ly)
tænder=light(s) / turn(s) on
tænker=think(s)
tænkt=thought
uddannelsen=the education
uddannelserne=the educational programmes
uddannelsessystemet=the education system
uddybe=to elaborate on
udenad=by heart
udfordring=challenge
udgift=expense
udleveres=be handed out
udsagn=statement(s)
udslippet=the emission(s)
udtryk=expression
udviklingen=the development
uenig=in disagreement
uenighed=disagreement
uklar=unclear
ukrainske=Ukrainian
understrege=to emphasise
understreger=emphasise(s)
undersøgelser=studies / surveys
undersøger=investigate(s)
undervise=to teach
undgå=to avoid
undskyld=sorry
universitetet=the university
usund=unhealthy
utilfredse=dissatisfied
utæt=leaky
valg=choice / election
valgretsalderen=the voting age
varm=warm
vejen=the road / the way
vennerne=the friends
venstre=left (til venstre = to the left)
viden=knowledge
video=video
vinteren=the winter
virkelig=really
virket=worked
virksomhed=company
virksomhederne=the companies
vist=shown
vågner=wake(s) up
vægt=weight / emphasis
weekend=weekend
årstid=season
årstiderne=the seasons
ældreplejen=elderly care
ændrede=changed
ændret=changed
økonomimedarbejder=finance officer
øl=beer
aalborg=Aalborg (city)
nørrebro=Nørrebro (part of Copenhagen)
vejle=Vejle (city)
teheran=Tehran
ukraine=Ukraine
sydfyn=South Funen (region)
søndergade=(street name)
torvet=the square
adam=(a name)
ahmadi=(a name)
amina=(a name)
anne=(a name)
birgitte=(a name)
henrik=(a name)
ivan=(a name)
karim=(a name)
kovalenko=(a name)
lene=(a name)
lina=(a name)
line=(a name)
mia=(a name)
mohammed=(a name)
morten=(a name)
mortensen=(a name)
mortensens=(a name)
nadia=(a name)
olena=(a name)
omar=(a name)
pia=(a name)
rahimi=(a name)
rasmus=(a name)
reza=(a name)
saleh=(a name)
signe=(a name)
sofie=(a name)
yusuf=(a name)
danskklar=DanskKlar ("ready for Danish")
niveauerne=the levels
sagt=said (kort sagt = in short)
uofficielt=unofficial
øveprogram=practice program
afholder=hold(s) (exams)
is=ice cream / ice
sommeren=the summer
a-g=A to G
a-f=A to F
motivationen=the motivation
computere=computers
solidt=solid
skifte=to change / to switch
letteste=easiest
installér=install
installerer=install(s)
installeret=installed
iphone=iPhone
ipad=iPad
knappen=the button
firkanten=the square
pilen=the arrow
nederst=at the bottom
safari=Safari (web browser)
føj=add (føj til = add to)
hjemmeskærm=home screen
hjemmeskærmen=the home screen
tilføj=add
absolut=absolutely
adækvat=adequate
afdelingen=the ward / the department
aflåst=locked (aflåst sideleje = recovery position)
afrejsedag=departure day
afslapning=relaxation
afslappende=relaxing
afslutte=to end / to finish
aftener=evenings
aftenskolen=the evening school
aftenvagt=evening shift
akkompagneres=is accompanied
aktivitetshus=activity house
aktivitetstilbud=activities on offer
almindelige=ordinary
almindeligt=common / normal
alting=everything
altså=well / so
anbefaling=recommendation
anbefalingen=the recommendation
ankomst=arrival
anmelde=to review
anmeldelse=review
annoncerne=the advertisements
apotek=pharmacy
apoteket=the pharmacy
april=April
arbejdsgiverne=the employers
arbejdsmiljø=working environment
arbejdstiderne=the working hours
arkiv=archive
arkæologi=archaeology
arr=organiser (arr.)
artister=artists
august=August
babybad=baby bath
bade=to swim / to bathe
badevand=bathing water
badning=bathing / swimming
baggrunden=the background
banegården=the railway station
bede=to ask
beder=ask(s)
bedsteforældre=grandparents
bedømmerark=assessment sheet
begrundede=justified / gave reasons for
begrundelse=reason / justification
begrunder=justify / give reasons
begynde=to begin
begyndelse=beginning
begyndt=begun / started
behandle=to treat
behøver=need(s) (behøver ikke = don't need to)
bekymret=worried
benzin=petrol
beskrev=described
beskrevet=described
beskrivelse=description
beskriver=describe(s)
beslutning=decision
beslutningen=the decision
besparelser=savings
bestod=passed
besvarer=answer(s)
besøgende=visitors
betaler=pay(s)
betalt=paid
betjening=service
bevis=certificate
bevægelse=movement
billard=billiards
billede=picture
billeder=pictures
billedet=the picture
billige=cheap
birkestamme=birch trunk
bod=stall
boldbaner=ball courts
boldspilsareal=ball-game area
bordtennis=table tennis
bordtennishal=table tennis hall
borgere=citizens / residents
botanisk=botanical
brasilianske=Brazilian
bredt=wide
brugskunst=applied art / design objects
bugner=is bursting (with)
buket=bouquet
buschauffør=bus driver
bussen=the bus
busstoppested=bus stop
butikker=shops
butikkerne=the shops
butikschefen=the store manager
butikslokale=shop premises
bybusser=city buses
byer=towns / cities
byerne=the cities
bygge=to build
bygger=build(s)
byskolen=the town school
byvandring=town walk
bytorv=town square
bådpladser=boat moorings
bådslip=slipway
bådudlejning=boat rental
bål=bonfire
børnebiffen=the children's cinema
børnebruser=children's shower
børneinstitutionen=the childcare institution
børnepool=children's pool
børneteater=children's theatre
børnetøj=children's clothes
børnevenlig=child-friendly
børneværelset=the child's room
café=café
caféer=cafés
camping=camping / campsite
campingplads=campsite
campingpladsen=the campsite
campingpladser=campsites
campingskiltene=the campsite signs
campingvogne=caravans
censors=the examiner's
chauffører=drivers
chef=boss
chefen=the boss / the manager
chokolade=chocolate
chokoladen=the chocolate
chokolader=chocolates
cirkus=circus
cykel-campister=cycle campers
cykelmuligheder=cycling opportunities
cykelsti=cycle path
cykelture=bike rides
cykeludlejning=bike rental
cyklister=cyclists
dagvagt=day shift
dametøj=women's clothing
dans=dance
delprøver=sub-tests / exam parts
deltagere=participants
dengang=back then
dens=its
dimser=gadgets / bits and pieces
dippedutter=knick-knacks
diverse=various
dreng=boy
drej=turn
drejes=turn
drevet=run (operated)
drikke=to drink
driver=run(s) (a business)
dukker=dolls / dummies
dygtig=skilled
dykning=diving
dyrehave=deer park
dyrehaven=the deer park
dyrke=to do (sport) / to grow
dårlig=bad
dårlige=bad
dækkende=covering / adequate
dækket=covered
e-mail=email
efterspurgte=sought-after
efteråret=the autumn
egentlig=actually
ejendom=property / building
eksaminators=the examiner's
elevator=lift
eneste=only
enestående=unique / outstanding
enhed=unit / pitch
enkelt=single
enlig=single (unmarried)
erhvervsrådgiver=business adviser
erhvervsskolen=the vocational school
erindringsdans=reminiscence dance
etableret=established
etc=etc.
falder=fall(s) (falder til ro = calm down)
familiebaderum=family bathroom
familiebaderummene=the family bathrooms
familielivet=family life
familieplads=family campsite
familierum=family room
faren=the father
farver=colours
fastansættelse=permanent employment
femstjernede=five-star
ferielejligheder=holiday flats
ferieoplevelse=holiday experience
filmforevisning=film screening
fiskemuligheder=fishing opportunities
fiskeri=fishing
fitness=gym / fitness
fjord=fjord
fjorden=the fjord
flest=most
flyttede=moved
fodre=to feed
folketro=folk belief
foran=in front of
forberedt=prepared
forbi=past / by (kig forbi = drop in)
foredrag=talk / lecture
forefindes=is available
forestillinger=performances
foretrækker=prefer(s)
forgrunden=the foreground
forhold=conditions / facilities
forholdsvis=relatively
forhåndstilmelding=advance registration
forklarede=explained
forklarer=explain(s)
forkæl=treat (yourself)
forlystelsespark=amusement park
formiddagen=the morning
forretning=business / shop
forretningsplan=business plan
forsalg=advance sale
forsigtigt=carefully
forsinket=delayed
forstyrre=to disturb
fortalte=told
fortrudt=regretted
forvejen=(i forvejen = in advance)
forår=spring
forårsnyheder=spring news / new spring items
forårstilbud=spring offer
fotografen=the photographer
fotografi=photography
friarealer=open spaces
frilandsmuseum=open-air museum
friskbagt=freshly baked
friske=fresh
frisørsalon=hair salon
frisøruddannelse=hairdressing training
frugt=fruit
fryser=freezer
fuld=full
fylder=take(s) up space
fyldt=filled
fænomen=phenomenon
færdiguddannet=fully qualified
født=born
følte=felt
førstehjælp=first aid
gader=streets
gaming=gaming
genbrug=recycling / second-hand
genbrugs=second-hand
genbrugsbutik=second-hand shop
genbrugsbutikker=second-hand shops
genbrugsting=second-hand things
genbrugstøj=second-hand clothes
generalisering=generalisation
generelle=general
generelt=generally
gentaget=repeated
gl=old (Gl. = Gammel)
glas=glass(es)
glatte=slippery
glæde=joy
grad=degree (i høj grad = to a great extent)
grillbar=grill bar
grillcafé=grill café
græs=grass
græsplænen=the lawn
grøntsager=vegetables
guitar=guitar
gulerødder=carrots
gulvet=the floor
gynger=swings
gågaden=the pedestrian street
gæst=guest
gæster=guests
gætte=to guess
halvmaraton=half marathon
halvtag=open shed / canopy
halvø=peninsula
handel=deal / trade
handicap=disability
handicaptoilet=accessible toilet
handling=action / plot
haveforeninger=allotment associations
havet=the sea
havn=harbour
havnebad=harbour bath
havnebadet=the harbour bath
havnebygningen=the harbour building
helligt=holy (holdes helligt = kept sacred)
hippe=hip / trendy
historien=history / the story
hjemlande=home countries
hjemløs=homeless
hjemmebagt=home-baked
hjemmeplejen=home care
hjemmeside=website
hjertemassage=CPR / heart massage
hjorte=deer
hjælpsomt=helpful
hjørnet=the corner
holdes=is held
holdstart=course start
hoppepude=bouncy pillow
hoppepuder=bouncy pillows
hoppet=jumped
hospital=hospital
hospitaler=hospitals
hospitalet=the hospital
hotel=hotel
hoteller=hotels
hotellet=the hotel
hotellets=the hotel's
hotspot=hotspot
hovedtrappen=the main stairs
hunden=the dog
husarbejde=housework
husarbejdet=the housework
husbådene=the houseboats
husdyr=pets
husordenen=the house rules
hverken=neither
hylde=shelf
hytter=cabins
hånden=the hand
hår=hair
hårpleje=hair care
hænge=to hang (hænge sammen = fit together)
højst=at most
høns=hens
høres=be heard
ideel=ideal
ideelle=ideal
idyl=idyll
idylliske=idyllic
ikoninspireret=icon-inspired
indeholde=to contain
indenfor=inside / within
indkøbskurven=the shopping basket
indkøbsliste=shopping list
indkøbstur=shopping trip
indsamle=to collect
infoskilt=information sign
inkl=incl.
inklusive=including
installationer=installations / facilities
institution=institution / nursery
instruktør=instructor
interesserer=interest(s) (interessere sig for = be interested in)
interesseret=interested
internet=internet
inviter=invite
invitere=to invite
inviterer=invite(s)
irriteret=annoyed
jomfru=virgin
jomfrudom=virginity
jomfruen=the virgin
jomfrumyterne=the virgin myths
juli=July
juni=June
kaffen=the coffee
kaj=quay
kajhygge=cosy time on the quay
kant=edge
karruseller=merry-go-rounds
kasse=box / till
kat=cat
kh=hugs (kærlig hilsen)
kig=look
kilo=kilo(s)
kiosk=kiosk
klagen=the complaint
klan=clan
klippe=to cut
klokken=o'clock / the clock
klubben=the club
km=km
kolonihave=allotment garden
kolonihaven=the allotment garden
kommoder=chests of drawers
kommunikation=communication
koncerter=concerts
kontrolcentret=the control centre
kor=choir
koste=to cost
kurser=courses
kurset=the course
kulturfestival=cultural festival
kulturhus=culture centre
kunst=art
kunsteffekter=art objects
kunsthåndværksboder=craft stalls
kunstmuseum=art museum
kunstnere=artists
kunstskibet=the art ship
kunstvandring=art walk
kup=bargain (gøre et kup = get a bargain)
kø=queue
køen=the queue
køkkenmedhjælper=kitchen assistant
køreplanen=the timetable
lader=let(s)
lager=storeroom / warehouse
lageret=the storeroom
lagt=put / placed
lavere=lower
leg=play
legeområde=play area
legeplads=playground
legepladsen=the playground
leger=play(s)
legerum=play room
leje=rent
ledige=vacant
levede=lived
leveret=delivered
ligeledes=likewise
live-koncert=live concert
livredder=lifeguard
lokaler=premises / rooms
lokalhistoriske=local history
loppefund=flea-market finds
loppejagt=flea-market hunting
loppemarkeder=flea markets
loppemarkedet=the flea market
lopper=flea-market items
loppetæmmere=flea-market dealers
loungeområde=lounge area
lovede=promised
lover=promise(s)
lukker=close(s)
luksuscampingvogne=luxury caravans
luksushytter=luxury cabins
lysbilledforedrag=slide-show talk
lysende=illuminated
lystbådehavn=marina
lystfiskere=anglers
lystfiskeri=angling
lyt=listen
lytteren=the listener
låne=to borrow / to lend
lægge=to put / to lay
lækre=lovely / delicious
læreruddannelsen=teacher training
læsepladser=reading places
løbetur=run / jog
lønnen=the pay
lørdag-lørdag=Saturday to Saturday
lørdagen=Saturday
madlavning=cooking
madvanerne=the eating habits
madvarer=food items
maj=May
male=to paint
maleri=painting
mangel=shortage
marina=marina
marinaen=the marina
maritim=maritime
markedet=the market
medicin=medicine
megen=much
melder=sign(s) up (melde sig)
meldte=signed up (meldte sig ind = joined)
meninger=opinions
midnat=midnight
midten=the middle
miljøet=the environment
minde=to remind
minigolfbane=mini-golf course
minimarked=mini-market
minut=minute
mirakel=miracle
mobil=mobile phone
mobilen=the mobile phone
modebevidste=fashion-conscious
moderne=modern
modtage=to receive
montre=display case
moren=the mother
morgenbrød=breakfast bread
morgenmaden=the breakfast
motiver=motifs / subjects
motorbåde=motorboats
motorcykel=motorcycle
mulig=possible
mulige=possible (alle mulige = all kinds of)
mulighederne=the possibilities
mundtlige=oral
museum=museum
måder=ways
måltid=meal
måltider=meals
møbelkræmmere=furniture dealers
møbler=furniture
møblerne=the furniture
mødested=meeting point
mødt=met
mønttelefon=payphone
møntvaskeri=coin laundry
mørklægningsgardiner=blackout curtains
naboernes=the neighbours'
nabos=neighbour's
nat=night
nattevagt=night shift
nattevagter=night shifts
natur=nature
naturskønne=scenic
naturskønt=scenically
nem=easy
netop=exactly / precisely
nogenlunde=reasonably / fairly
nostalgikoncert=nostalgia concert
nyde=to enjoy
nylig=(for nylig = recently)
nyrenoveret=newly renovated
nær=near
nærmere=more closely
nærmeste=nearest
nævnte=mentioned
nødvendig=necessary
oase=oasis
omgående=immediate
omsorg=care
omvendt=the other way round
område=area
området=the area
opbygning=structure
opera=opera
opholdsrum=common room
opklarende=clarifying
oplevelse=experience
oplevelser=experiences
oplevelsesparken=the adventure park
opleves=be experienced
oplysningerne=the information
opmuntre=to encourage
oprindelige=original
oprydningsudsalg=clearance sale
oprør=rebellion
opvarmet=heated
ordbøger=dictionaries
ordene=the words
overholde=to keep to
overnatning=overnight stay
overskud=profit / surplus
parasol=parasol
park=park
parkeringspladsen=the car park
pas=passport
passager=passenger
passagerer=passengers
passagererne=the passengers
passede=looked after
passet=looked after
patient=patient
patienterne=the patients
pc=PC
pendlere=commuters
perioden=the period
personale=staff
personalet=the staff
personen=the person
personerne=the people
personlig=personal
pianist=pianist
picnic=picnic
piger=girls
pigerne=the girls
placeret=placed
pladsen=the site / the place
pladser=pitches / places
planer=plans
planlægger=plan(s)
plejehjemmet=the nursing home
plejer=usually do(es)
pollensæsonen=the pollen season
port=gate
postkasse=letterbox
pr=per
prisbelønnede=award-winning
priserne=the prices
privat=private
projekt=project
præmier=prizes
præsentation=presentation
præsentationen=the presentation
prøvedeltager=test candidate
prøveklar=exam-ready
prøveopgave=exam task
prøveopgaver=exam tasks
pusle=changing (pusle-rum = baby-changing room)
puslerum=baby-changing room
radio=radio
rart=nice
regionale=regional
regn=rain
regnbue=rainbow
rene=clean
rengøringsassistent=cleaner
rengøringshjælp=cleaning help
retfærdigt=fair
retning=direction
retro=retro
rette=right (den rette = the right person)
retter=dishes
revolte=revolt
rige=rich / plenty of
risalamande=Danish rice pudding
rolig=calm
rundstykker=bread rolls
rydde=to tidy (rydde op = tidy up)
ryddet=tidied / cleared
rygsæk=backpack
rykker=move(s)
rytmik=rhythmics
råber=shout(s)
rådhus=town hall
rådne=rotten
råvarer=ingredients
sagde=said
salat=salad
salon=salon
salonen=the salon
sammenhæng=coherence
samtalepartneren=the conversation partner
sangen=the song
sangere=singers
sanitære=sanitary
sauna=sauna
savnede=missed
seddel=note
sejl=sail
sejlads=sailing
sejlere=sailors
selvkørende=self-driving
sengene=the beds
serverer=serve(s)
servicebygning=service building
shoppefund=shopping finds
shopping=shopping
sideleje=(aflåst sideleje = recovery position)
sjovere=more fun
sjældent=rarely
skaffe=to get / to obtain
skak=chess
sker=happen(s)
sket=happened
skibsværft=shipyard
skift=change
skifter=change(s)
skiftet=changed
skilt=divorced
skraldespand=bin
skrivebord=desk
skynder=hurry (skynde sig)
skånes=are spared
skærme=screens
skønnest=most beautifully
slags=kind(s) / sort(s)
slavebaggrund=background in slavery
slemt=bad
slotspark=castle park
slutning=ending
slægt=family / lineage
smager=taste(s)
smart=smart / stylish
smiler=smile(s)
smykker=jewellery
småting=small things
snakket=talked
social=social
socialt=social(ly)
sodavand=soft drink
solarium=solarium
solgt=sold
solskin=sunshine
sommerferielukket=closed for summer holiday
sommerhuse=holiday cottages
sommermarkedet=the summer market
sommervejr=summer weather
sopran=soprano
sortere=to sort
sov=slept
sover=sleep(s)
sovesofa=sofa bed
sovet=slept
spabad=hot tub
spare=to save
sporvognsremise=tram depot
stadeholdere=stallholders
stadepladser=pitches
staderne=the stalls
stande=stalls
station=station
statsfuglereservat=state bird reserve
stede=present (til stede)
stedets=the place's
stemning=atmosphere
stenkast=stone's throw
stilhed=silence
stillede=asked / put
stjerner=stars
stk=pcs. (pieces)
stoppet=stopped
striber=stripes
strik=knit
strikkecafé=knitting café
strikkecafe=knitting café
strikkecaféen=the knitting café
stræde=lane
strøm=electricity
studiekort=student card
stueplanter=houseplants
støvsuge=to vacuum
sunde=healthy
sundere=healthier
sundhedshjælper=health care assistant (social- og sundhedshjælper)
supermarked=supermarket
suppe=soup
surfere=surfers
svømmebad=swimming pool
swimmingpool=swimming pool
sy=to sew
syd=south
symaskiner=sewing machines
synger=sing(s)
syning=sewing
syntes=thought
særlig=special / particularly
sødt=sweet things
søges=wanted
sølvringe=silver rings
søndagstoner=Sunday tunes
tableau=tableau
tabt=lost
tapas=tapas
tegnefilmen=the cartoon
telt=tent
tennisbaner=tennis courts
terrassen=the terrace
terrængolf=cross-country golf
tidspunkt=time / moment
tilbringer=spend(s) (time)
tilbyde=to offer
tilladt=allowed
tilmeld=sign up
tilmelder=sign(s) up
tiltrædelse=start (of a job)
tingene=the things
tips=tips
tirsdag=Tuesday
toiletforhold=toilet facilities
trafikskole=driving school
trampolin=trampoline
transporten=the transport
trapper=stairs
trave=hiking
travlt=busy
trestjernet=three-star
tropiske=tropical
truck=forklift truck
træet=the tree
træneren=the coach
tulipaner=tulips
turistbureau=tourist office
turneringen=the tournament
tv-stue=TV room
tænk=think
tænke=to think (tænke sig = would like)
tættere=closer
tømt=emptied
tømte=emptied
tørretumbler=tumble dryer
uddanne=to train / to educate
uddannet=trained / qualified
uddybende=elaborating
udendørs=outdoor
udendørsmarked=outdoor market
udenfor=outside
udflugter=excursions
udfoldelsesmuligheder=opportunities for activities
udgangspunkt=starting point
udland=abroad
udlejer=rent(s) out
udlejes=for rent
udlejning=rental
udstiller=exhibit(s)
udtale=pronunciation
udtrykker=express(es)
udvikle=to develop
ugens=the week's
ugerne=the weeks
underholdning=entertainment
underviseren=the teacher
undervisning=teaching / lessons
undskylder=apologise(s)
upcycling=upcycling
ur=watch / clock
ure=watches / clocks
vagt=shift
valgfri=optional
valgt=chosen
valgte=chose
vand=water
vandaktiviteter=water activities
vandet=the water
vandre=hiking
vandreture=hikes
vandsport=water sports
varede=lasted
varmt=warmly
vaser=vases
vaske=to wash
vaskemaskiner=washing machines
vaskeri=laundry
vasketøj=laundry
velegnet=suitable
velkomst=welcome
veninde=(female) friend
venligt=kind
ventelister=waiting lists
venter=wait(s)
videoredigering=video editing
vidst=known
vigtige=important
vigtigst=most important
vigtigste=most important
vikar=temp / substitute
vild=wild (vild med = crazy about)
vintage=vintage
vise=to show
viste=showed
visum=visa
voksen=adult
voldene=the ramparts
vore=our
vred=angry
væksthuse=greenhouses
værelserne=the rooms
værket=the work (of art)
værre=worse
webshop=web shop
weekenderne=the weekends
weekendtilbud=weekend activities
windsurfing=windsurfing
workshop=workshop
workshops=workshops
yoghurt=yoghurt
årene=the years
årige=year-olds
æblekage=apple cake
æg=egg(s)
ældre=elderly / older
ændringer=changes
ærgerligt=a pity
æske=box
æsken=the box
æsker=boxes
ø=island
øen=the island
økonomi=finances
økonomiske=economic
ørepropper=earplugs
øvesæt=practice set
albert=(a name)
alex=(a name)
amal=(a name)
amini=(a name)
anders=(a name)
ane=(a name)
benoni=(a name)
birthe=(a name)
giulia=(a name)
grace=(a name)
haddad=(a name)
hassan=(a name)
hjalmer=(a name)
inge=(a name)
jacks=(a name)
johnny=(a name)
julian=(a name)
kasper=(a name)
klaus=(a name)
kristensen=(a name)
kurt=(a name)
larsen=(a name)
leila=(a name)
leyla=(a name)
mads=(a name)
magnus=(a name)
marco=(a name)
mis=(a name)
munksgaard=(a name)
nabiha=(a name)
nguyen=(a name)
ole=(a name)
omid=(a name)
pernille=(a name)
per=(a name)
rasmussen=(a name)
rita=(a name)
rossi=(a name)
ruth=(a name)
ruths=(a name)
sam=(a name)
samira=(a name)
samiras=(a name)
schmidt=(a name)
steffen=(a name)
søren=(a name)
sørensen=(a name)
therkel=(a name)
thomas=(a name)
vagn=(a name)
victor=(a name)
willumsen=(a name)
yonas=(a name)
ellis=(a name)
gabriella=(a name)
pace=(a name)
kolstrup=(a name)
cornelins=(a name)
geertsen=(a name)
aros=(place / street name)
algade=(place / street name)
als=(place / street name)
arnbjergvej=(place / street name)
augustenborg=(place / street name)
augustenhof=(place / street name)
augustenhofvej=(place / street name)
axeltorv=(place / street name)
bangladesh=(place / street name)
bispeengbuen=(place / street name)
broager=(place / street name)
brøndby=(place / street name)
bystævnevej=(place / street name)
carlsberg=(place / street name)
emdrup=(place / street name)
elmegade=(place / street name)
enghavevej=(place / street name)
engparken=(place / street name)
engvej=(place / street name)
eritrea=(place / street name)
farum=(place / street name)
fjordvej=(place / street name)
flensborg=(place / street name)
frederiksberg=(place / street name)
fynshav=(place / street name)
gendarmstien=(place / street name)
gråsten=(place / street name)
havnefronten=(place / street name)
havremarken=(place / street name)
horsens=(place / street name)
husum=(place / street name)
indien=(place / street name)
kegnæs=(place / street name)
klaragade=(place / street name)
kolding=(place / street name)
lavensby=(place / street name)
libanon=(place / street name)
lillebælt=(place / street name)
lillebæltvej=(place / street name)
lundebakken=(place / street name)
lysabildskov=(place / street name)
madeskov=(place / street name)
mommark=(place / street name)
mommarkvej=(place / street name)
nakskov=(place / street name)
nakskovs=(place / street name)
nattergalevej=(place / street name)
nederbyvej=(place / street name)
nordborg=(place / street name)
pasteursvej=(place / street name)
refshalevej=(place / street name)
refshaleøen=(place / street name)
ringgade=(place / street name)
rinkenæs=(place / street name)
skagen=(place / street name)
skeldebro=(place / street name)
skibbroen=(place / street name)
skibbroens=(place / street name)
skovbrynet=(place / street name)
skovby=(place / street name)
skovforten=(place / street name)
sydals=(place / street name)
sydamerika=(place / street name)
sønderborg=(place / street name)
sønderby=(place / street name)
sønderbygade=(place / street name)
sønderjylland=(place / street name)
viborg=(place / street name)
vingsted=(place / street name)
østerbyvej=(place / street name)
østergade=(place / street name)
østersøen=(place / street name)
stavensbøl=(place / street name)
banegårdsgade=(place / street name)
dokk1=(place / street name)
dokk=(place / street name)
moesgaard=(place / street name)
marselisborg=(place / street name)
croix=(place / street name)
format=format
rollespil=role play
niveauet=the level
domæne=domain / territory
boulevarden=the boulevard
fremover=from now on
panoramablik=panoramic view
funracer=go-kart
netcafé=internet café
former=forms / kinds
barnlige=childlike
max=max.
månedlig=monthly
krukker=pots
frøken=miss
teoriundervisning=theory lessons
allergi=allergy
kvalitetsmøbler=quality furniture
th=right (th. = til højre, flat on the right)
st=ground floor (st. = stuen)
bank=bank
sygeplejersker=nurses
kollegaen=the colleague
el=electricity
pizza=pizza
sent=late
an=(kommer an på = depends on)
skt=Saint (Skt.)
wc=toilet (WC)
sv=SW (south-west)
nv=NW (north-west)
dr=DR (Danish public broadcaster)
tivoli=Tivoli (amusement park)
friheden=Friheden (park name)
netto=Netto (supermarket chain)
facebook=Facebook
hitler=Hitler
volkswagen=Volkswagen
garageanlægget=the garage complex
toldbodkajen=the customs-house quay
toldboden=the customs house
atriumgården=the atrium courtyard
vestinder=West Indian
dieselskandalen=the diesel scandal
tryllefløjten=The Magic Flute (nursery name)
skolebakken=(name of a care home)
skovcentret=(name of a care centre)
loppetorv=flea-market square
loppelunden=(name of a flea market)
rådhustorvet=the town hall square
spejdernes=(a name)
veras=(a name)
svalernes=(a name)
furesøens=(a name)
hertugbyens=(a name)
lærkelunden=(a name)
møllers=(a name)
bibiana=(a name)
changhigh=(a name)
tivolidrengens=(a name)
sydhavnsøerne=(a name)
husteds=(a name)
nisu=(a name)
viola=(a name)
strandly=(a name)
copenhagens=(a name)
kph=(a name)
tap=(a name)
universe=(a name)
szhirley=(a name)
ultramarin=(a name)
deluxe=(a name)
fætr=(a name)
bro=(a name)
dyrlund=(a name)
skinz=(a name)
liga=(a name)
dabuf=(a name)
anduin=(a name)
nakskovkultur=(a name)
aok=(a name)
visitsonderborg=(a name)
affald=rubbish
afhentning=collection (must be picked up)
afleveret=dropped off / handed in
afmeld=unsubscribe
aftenshowet=the evening show
afveje=detours (på afveje = astray)
aktiv=active
akademi=academy
alkohol=alcohol
amerikaner=American
amerikanske=American
andel=share (co-op price)
andelsbolig=co-operative flat
anlæg=park / gardens
ansigt=face
ansøgningsfrist=application deadline
antal=number
arbejdsdage=working days
arbejdslønnen=the labour cost
arbejdsløsheden=unemployment
arrangere=to arrange
astronomen=the astronomer
auto=car dealer
automobiler=cars
avisen=the newspaper
badeværelset=the bathroom
bagage=luggage
bage=to bake
baglokale=back room
bamse=teddy bear
band=band
banken=the bank
bebygget=built on
befinder=find(s) oneself (befinde sig = be)
begavede=gifted
begivenhederne=the events
begreb=concept
beretning=account / story
bestået=passed
besøgsven=visiting friend (volunteer)
betal=pay
betjent=police officer
betydning=significance
bevidst=aware
billederne=the pictures
blinkende=flashing
blodtryk=blood pressure
blomsterauktioner=flower auctions
blåmetal=metallic blue
bog=book
bordeaux=burgundy (colour)
bordeauxmetal=metallic burgundy
borgerkrig=civil war
brdr=Bros. (Brødrene)
bringer=deliver(s) / bring(s)
bror=brother
brugervenlig=user-friendly
bryllup=wedding
brætspil=board game
brødrister=toaster
busholdeplads=bus stop
busrute=bus route
busruter=bus routes
bustur=coach trip
bålplads=campfire site
bær=berries
bærer=carry / carries
børne-tv=children's TV
caféen=the café
cd=CD
cigaretter=cigarettes
computerspil=computer games
coupé=coupé
daglige=daily
dame=lady
dankort=Dankort (debit card)
dankortet=the debit card
dansede=danced
danskernes=the Danes'
debatten=the debate
delte=shared
dessert=dessert
diesel=diesel
dir=live (dir. = direkte)
doktor=doctor
dokumentaren=the documentary
drab=killing(s)
drengen=the boy
drengenavne=boys' names
driftige=enterprising
dronning=queen
druknede=drowned
drøm=dream
dværg=dwarf
dværgen=the dwarf
dyrene=the animals
dyrenes=the animals'
dækker=cover(s)
dødedans=dance of death
døgn=day and night (24 hours)
dørs=door (5-dørs = five-door)
dørtrin=doorstep
efterfølgende=afterwards
efterladte=those left behind
efterlod=left (behind)
eje=to own
energi=energy
engang=once
enken=the widow
familiefest=family party
familiekrønike=family chronicle
familiemiddag=family dinner
fandt=found
fangarme=tentacles
fangenskab=captivity
fantasifulde=imaginative
far=father
feriebilleder=holiday photos
finans=finance
finansminister=finance minister
fisk=fish
fiskerkone=fisherman's wife
fiskerkonen=the fisherman's wife
fjerkræ=poultry
fjernb=remote locking (fjernb. = fjernbetjening)
fjernsyn=television
flad=flat
fliser=tiles
fliserne=the tiles
fløjte=whistle
fodboldklub=football club
foder=animal feed
forelsker=fall(s) in love
forfatteren=the author
forfædre=ancestors
forlag=publisher
formue=fortune
fornavne=first names
forret=starter
forskelligt=different / various
forsvunden=lost / missing
forsvundne=missing
forvandling=transformation
forventer=expect(s)
forårsrejse=spring trip
foræres=is given as a present
framelde=to unsubscribe
fremmed=strange / foreign
fremmede=strangers
frisører=hairdressers
frivilligt=voluntary
frues=Lady's (Vor Frue = Our Lady)
fødselslæge=obstetrician
følger=follow(s) / consequences
ganske=quite
gear=gear
generationer=generations
genindsatte=reinstated
gensyn=reunion
gifter=marr(ies)
gjorde=did / made
glæden=the joy
gnaver=rodents
gnidningerne=the friction
gravid=pregnant
griller=barbecue(s)
gruppe=group
gruppen=the group
gråmetal=metallic grey
grænsepatruljen=the border patrol
græsrødder=grassroots
grønmetal=metallic green
guders=gods'
guider=guides
guld=gold
guldalderens=of the Golden Age
guldsmeden=the goldsmith
guldsmykker=gold jewellery
gummistøvler=wellies
hånd=hand
håndbold=handball
håndværkere=craftsmen / workmen
hænder=hands
hævnen=the revenge
høflig=polite
højt=aloud / high
handelsborgerskab=merchant class
handy=handy
haves=available (for swap)
healer=healer
healeren=the healer
hedninge=heathens
held=luck (held og lykke = good luck)
helte=heroes
henviser=refer(s)
herremandens=the lord of the manor's
hest=horse
historier=stories
historisk=historical
historiske=historical
hjuldamper=paddle steamer
hjulpet=helped
hjælpsomhed=helpfulness
hjælpsomme=helpful
hoste=to cough
hoster=cough(s)
hoveddøren=the front door
hovedret=main course
hovedvagten=the main guardhouse
humør=mood
hurtige=quick
hustru=wife
hverdagsmad=everyday food
hvid=white
hygge=cosiness
hyres=is hired
ikke-ryger=non-smoker
illustration=illustration
indkøbsvogn=shopping trolley
indtil=until
inkvisitionen=the Inquisition
inspiration=inspiration
invalide=disabled
januar=January
karismatiske=charismatic
kaldet=called
kamera=camera
kameraet=the camera
kanal=channel
ked=sad (ked af = sorry about)
kede=sad
kejser=emperor
kilder=sources
klassekammerater=classmates
klatre=to climb
klinikken=the clinic
koksmetal=metallic charcoal
kolesterol=cholesterol
kompetente=competent
koncentreret=focused
konfirmation=confirmation
konflikt=conflict
kong=king
konge=king
kongelige=royal
kongen=the king
konkurrencen=the competition
konsekvenserne=the consequences
kontaktes=be contacted
kontanter=cash
kortfattet=brief
kost=diet
krigsforbryder=war criminal
krigsveteran=war veteran
kriminalkommissær=detective chief inspector
kristne=Christians
krones=is crowned
krybdyr=reptiles
kræfter=forces / powers
kufferter=suitcases
kulturhuset=the culture centre
kulturpersonligheder=cultural figures
kunstnerisk=artistically
kvindekamp=women's struggle
kvindekommission=women's commission
kylling=chicken
kæledyr=pet
købmanden=the merchant
køkkenbord=kitchen counter
køkkenhave=vegetable garden
køleskabet=the fridge
køn=gender
kørestol=wheelchair
lagkage=layer cake
laks=salmon
lam=lamb
landeplagen=the national craze (hit song)
landsbyhospitalet=the village hospital
landsbykirke=village church
langvej=long road
latinamerikansk=Latin American
legede=played
legetøjsbutik=toy shop
lektiehjælper=homework helper
lever=live(s)
lig=dead body
lillametal=metallic lilac
lillebror=little brother
lillesøsters=little sister's
livs=life's (sit livs kærlighed = the love of her life)
livvagt=bodyguard
lokalavisen=the local newspaper
lort=crap
lygter=lights
lykke=happiness / luck
lykkelig=happy
lykken=happiness / fortune
lysets=light's
lå=lay
lån=loan
lækker=delicious
løsningen=the solution
madpakke=packed lunch
magtens=of power
manden=the man
maskine=machine
masse=lot (en masse = lots)
mdl=monthly (mdl.)
medlem=member
menu=menu
metal=metallic
mikrobølgeovn=microwave oven
montere=to install
mordet=the murder
munken=the monk
musikere=musicians
musikgruppe=music group
måske=maybe
mærkeligt=strange
mødet=the meeting
mødte=met
navne=names
nedlagt=closed / abolished
nordisk=Nordic
nordre=north(ern)
norske=Norwegian
nummer=number
nydelse=pleasure
nyheder=news
nyhederne=the news
nysynet=newly passed MOT
obs=note! (OBS!)
olivenolie=olive oil
ombygning=renovation
omdrejningspunkt=pivot / focus
omrejsende=travelling
onkel=uncle
opdager=discover(s)
opgang=stairwell (block entrance)
opmærksom=aware / attentive
opslaget=the notice
opsøge=to seek out
opvaskemaskine=dishwasher
ordenssans=sense of order
overklasse=upper class
p-plads=parking space
paa=on (old spelling of på)
papegøje=parrot
papir=paper
paradis=paradise
parcelvej=residential road
partner=partner
passion=passion
pasta=pasta
pauserne=the breaks
pave=Pope
pc-undervisning=PC lessons
pengepungen=the wallet
perron=platform
personlighed=personality
pigenavne=girls' names
plader=number plates
populære=popular
populært=popular
præcis=exactly
prærien=the prairie
prinsesse=princess
pung=wallet
purpur=purple
purpurfarversken=the purple dyer (woman)
putter=put(s) (putte i bad = give a bath)
regionalprogram=regional programme
regionalruter=regional routes
regnen=the rain
redningsmand=rescuer
redskabsskur=tool shed
reolerne=the shelves
restauranten=the restaurant
retterne=the dishes
rimelige=reasonable
ringede=rang / called
ris=rice
rock=rock music
rodet=messed up
rokker=wobbles
roman=novel
romaner=novels
romersk=Roman
ruder=windows / panes
rute=route
ruter=routes
ryge=to smoke
rygeforbud=smoking ban
ryger=smoke(s) / smoker
rygter=rumours
røg=smoke
saga=saga
sammensætte=to put together
sange=songs
sanger=singer
sat=put
satte=put / set
sedlen=the note
selskabslokale=party venue
selvbetjening=self-service
send=send
sene=late
service=service
servo=power steering
servostyring=power steering
sideallé=side avenue
sidelinjen=the sideline
sider=sides
sidetal=number of pages
sidevej=side road
simpelthen=simply
situation=situation
sjæl=soul
ske=happen
skibbruden=shipwrecked
skipperbyen=the sea captains' town
skjulte=hidden
sko=shoes
skolebladet=the school magazine
skolegade=school street
skylder=owe(s)
skævt=crooked
slottet=the palace
slægten=the family line
smagsdommerne=the tastemakers
smile=to smile
smykke=piece of jewellery
småkårsfolk=poor people
sommerhus=holiday home
sommerlørdag=summer Saturday
sorte=black
sortmetal=metallic black
specielle=special
spektakel=spectacle
spillede=played
spillekonsol=games console
spillet=played
spinat=spinach
spisebordet=the dining table
spist=eaten
sporløst=without a trace
sporten=the sport
spærrede=blocked
stemplet=branded / labelled
sten=stone
stok=walking stick
storesøster=big sister
storpolitik=high politics
strandturen=the trip to the beach
stykke=piece
sure=angry / sour
superlavenergi-ruder=super-low-energy windows
svage=weak
synet=passed MOT
sættes=is put
sø=lake
sødeste=sweetest
sølvmetal=metallic silver
sømand=sailor
sømænd=sailors
sørge=to make sure
søskende=siblings
søster=sister
tallets=century's (1400-tallets = 15th century's)
tante=aunt
telefonsvarer=answering machine
temmelig=rather
tidens=the time's
tilbehør=accessories
tilbragte=spent (time)
tilkaldes=is called in
tillykke=congratulations
tilsammen=together
tiramisu=tiramisu
tjekker=check(s)
tjene=to earn
tjenerne=the waiters
torsdagen=Thursday
tragiske=tragic
traktor=tractor
travl=busy
trommeslager=drummer
tronen=the throne
trækker=pull(s)
tulipanmarker=tulip fields
tung=heavy
tunge=heavy
turen=the trip
tv-programmer=TV programmes
typen=the type
tysker=German
tyv=thief
tyve=twenty / thieves
tyven=the thief
tæppe=blanket
tør=dare(s) / dry
tøven=hesitation
udarbejdet=prepared
udgifter=expenses
udgivet=published
udkommer=is published
udsmykke=to decorate
ulemperne=the disadvantages
umage=odd (et umage par = an odd couple)
underholde=to entertain
undvære=to do without
ung=young
ungdoms=youth's
unåde=disgrace
update=update
urter=herbs
vasket=washed
vejr=weather
vender=return(s) (vende hjem)
veninders=girlfriends'
venlige=friendly
verdens=the world's
verdenshavene=the oceans
vestre=western
videnskab=science
videoopkald=video call
vikingetid=Viking Age
vilde=wild
vildeste=wildest
vind=win
vitaminer=vitamins
vokse=to grow (vokse op = grow up)
voksenafdelingen=the adult section
vold=violence
voldsom=violent / dramatic
vor=our
vuggestue=nursery
vuggestuen=the nursery
vådt=wet
vågen=awake
vækker=wake(s) (someone)
vækkeuret=the alarm clock
værksted=workshop
værktøj=tools
weekendvagt=weekend service
ydelse=payment
åbenbart=apparently
århundrede=century
ægteskabet=the marriage
øje=eye (holde øje med = keep an eye on)
ønskes=wanted
øvelokale=rehearsal room
aaboulevarden=(a name)
aagade=(a name)
aalekistevej=(a name)
aars=(a name)
abs=(a name)
absalonsgade=(a name)
adelersborggade=(a name)
adelgade=(a name)
adolphsensgade=(a name)
agathes=(a name)
agerskov=(a name)
ahorns=(a name)
aid=(a name)
airc=(a name)
akademigade=(a name)
aksel=(a name)
alberte=(a name)
aldershvilevej=(a name)
alexander=(a name)
alexandria=(a name)
alfa=(a name)
alfred=(a name)
allende=(a name)
allerød=(a name)
alley=(a name)
alma=(a name)
amagerbro=(a name)
amagerbrogade=(a name)
amagervej=(a name)
amalie=(a name)
amsterdam=(a name)
andemosevej=(a name)
andersens=(a name)
andrea=(a name)
andreas=(a name)
angrib=(a name)
annemad=(a name)
anton=(a name)
antoniestræde=(a name)
antonigade=(a name)
antonio=(a name)
apollo=(a name)
aps=(a name)
arnborg=(a name)
arresøvej=(a name)
asta=(a name)
astra=(a name)
astrid=(a name)
asylgade=(a name)
atbiler=(a name)
atd-shoppen=(a name)
aunsbjerg=(a name)
babar=(a name)
backers=(a name)
badevej=(a name)
bagergade=(a name)
baggage=(a name)
baggesens=(a name)
bakkegaardsvej=(a name)
balsamgade=(a name)
bangs=(a name)
bangsvej=(a name)
barkmøllevej=(a name)
batterivej=(a name)
benjamin=(a name)
benkogerivej=(a name)
bennekevej=(a name)
bentsdatter=(a name)
beringsgade=(a name)
bernstorffsvej=(a name)
bertram=(a name)
beverly=(a name)
bianco=(a name)
biancogade=(a name)
bilal=(a name)
bispebjerg=(a name)
bjarkes=(a name)
bjørnegade=(a name)
blaagaards=(a name)
blaagaardsgade=(a name)
blaagaardsvej=(a name)
blaastjernevej=(a name)
blake=(a name)
blegdammen=(a name)
blegdamsvej=(a name)
blegedamsstræde=(a name)
blåhøj=(a name)
blæsbjerg=(a name)
boest=(a name)
bonnevie=(a name)
bording=(a name)
borgen=(a name)
boston=(a name)
boye=(a name)
brande=(a name)
bringstrupvej=(a name)
brogade=(a name)
bryggerlængen=(a name)
brynhildes=(a name)
brædstrup=(a name)
brøndstræde=(a name)
brønshøj=(a name)
bs=(a name)
bubber=(a name)
bygaards=(a name)
bygmesteren=(a name)
børglumvej=(a name)
børsen=(a name)
bülowsvej=(a name)
car=(a name)
carina=(a name)
carl=(a name)
carlsen=(a name)
caroline=(a name)
carsten=(a name)
cashmere=(a name)
castro=(a name)
cat=(a name)
cb=(a name)
cdx=(a name)
cecilie=(a name)
celina=(a name)
chokoladeskum=(a name)
chr=(a name)
christianshede=(a name)
christoffer=(a name)
cirkeline=(a name)
citro=(a name)
clara=(a name)
clare=(a name)
clausen=(a name)
clodia=(a name)
combi=(a name)
comedy=(a name)
comfort=(a name)
cops=(a name)
corsa=(a name)
cph=(a name)
cruiser=(a name)
daewoo=(a name)
dages=(a name)
daily=(a name)
dalslandsgade=(a name)
dam=(a name)
danasvej=(a name)
daniel=(a name)
david=(a name)
dba=(a name)
deadline=(a name)
diego=(a name)
disney=(a name)
dk-australien=(a name)
drantum=(a name)
druknehuset=(a name)
dsb=(a name)
dørslund=(a name)
ejstrupholm=(a name)
eksperimentet=(a name)
elantra=(a name)
elias=(a name)
ella=(a name)
elne=(a name)
elskede=(a name)
emil=(a name)
emilie=(a name)
emma=(a name)
emnerne=(a name)
engebæk=(a name)
engelshjerte=(a name)
engesvang=(a name)
entourage=(a name)
erik=(a name)
ernst=(a name)
eskildsgade=(a name)
essentia=(a name)
estate=(a name)
esther=(a name)
evaldsgade=(a name)
evensen=(a name)
faber=(a name)
fabulerende=(a name)
fan=(a name)
fandango=(a name)
fanø=(a name)
fasanvej=(a name)
fasterholt=(a name)
faurholt=(a name)
fidel=(a name)
filip=(a name)
findus=(a name)
finlandsgade=(a name)
fischers=(a name)
fogtdal=(a name)
forbrydelsens=(a name)
fox=(a name)
frankrig=(a name)
frd=(a name)
fredericia=(a name)
fredericiagade=(a name)
frederik=(a name)
frederikke=(a name)
frederikshavn=(a name)
freja=(a name)
frida=(a name)
gammelvagt=(a name)
gislinge=(a name)
gjellerup=(a name)
glostrup=(a name)
gls=(a name)
gludsted=(a name)
glxi=(a name)
go=(a name)
gondrup=(a name)
grand=(a name)
grenaa=(a name)
grindsted=(a name)
grundtvigsvej=(a name)
guldbergsgade=(a name)
gunnar=(a name)
gustav=(a name)
gyldendal=(a name)
gyldne=(a name)
gyritegade=(a name)
haiti=(a name)
hammerum=(a name)
hampen=(a name)
haslev=(a name)
hdi=(a name)
helle=(a name)
helleberg=(a name)
helsingør=(a name)
hemmet=(a name)
herning=(a name)
hills=(a name)
hiroshima=(a name)
hirsch=(a name)
holbæk=(a name)
holkenfeldt=(a name)
holland=(a name)
hollænderen=(a name)
holmes=(a name)
hovedland=(a name)
hugo=(a name)
hygild=(a name)
hyundai=(a name)
højbjerg=(a name)
hørlych=(a name)
hørte=(a name)
ignis=(a name)
ih=(a name)
ikast=(a name)
ikast-brande=(a name)
ilskov=(a name)
ingeborg=(a name)
ingegerd=(a name)
inuit=(a name)
irmingersgade=(a name)
isabel=(a name)
isabella=(a name)
isenvad=(a name)
islevhusvej=(a name)
iv=(a name)
jacob=(a name)
jasmin=(a name)
jasminvej=(a name)
jeppe=(a name)
jeps=(a name)
jersild=(a name)
jette=(a name)
joey=(a name)
johan=(a name)
johanne=(a name)
johansson=(a name)
jonathan=(a name)
josefine=(a name)
julie=(a name)
julius=(a name)
juul=(a name)
jøder=(a name)
jødisk=(a name)
jørgen=(a name)
jørkov=(a name)
jørn=(a name)
jørns=(a name)
kaarsbøl=(a name)
kalahari-ørkenen=(a name)
karla=(a name)
karlsen=(a name)
karsten=(a name)
karstoft=(a name)
katholmvej=(a name)
katrine=(a name)
kia=(a name)
kim=(a name)
kirkeby=(a name)
kjædegaard=(a name)
kjærboe=(a name)
klovborg=(a name)
klump=(a name)
knudsgade=(a name)
kofod=(a name)
korsgade=(a name)
korsvej=(a name)
kristoffer=(a name)
kristus=(a name)
kurlandsgade=(a name)
kvik=(a name)
kystvejen=(a name)
la=(a name)
lamborghini=(a name)
landskronagade=(a name)
lanos=(a name)
lasse=(a name)
laura=(a name)
lea=(a name)
legal=(a name)
lehmann=(a name)
letterman=(a name)
levinsen=(a name)
liebhaverne=(a name)
limited=(a name)
lind=(a name)
lindhardt=(a name)
lindogravnholt=(a name)
linear=(a name)
litteratursiden=(a name)
liva=(a name)
livornovej=(a name)
ll=(a name)
lotusvej=(a name)
lotusvejs=(a name)
lucas=(a name)
luderliv=(a name)
lufthavnen=(a name)
lukkede=(a name)
luna=(a name)
lund=(a name)
lundsten=(a name)
lundstrøm=(a name)
lunos=(a name)
lærke=(a name)
løkkeberg=(a name)
madonna-maleren=(a name)
malou=(a name)
malthe=(a name)
marcus=(a name)
margrete=(a name)
marie=(a name)
marius=(a name)
marstal=(a name)
martha=(a name)
mathias=(a name)
mathilde=(a name)
mbiler=(a name)
mercedes=(a name)
mikkel=(a name)
mikkelsen=(a name)
mille=(a name)
miracle=(a name)
mitsubishi=(a name)
mogens=(a name)
monzes=(a name)
munklinde=(a name)
munksgade=(a name)
mv=(a name)
møbjerg=(a name)
mørk=(a name)
naja=(a name)
nanna=(a name)
naso=(a name)
nattesøvn=(a name)
nicklas=(a name)
nicoline=(a name)
niels=(a name)
nikolaj=(a name)
noah=(a name)
noahs=(a name)
noddy=(a name)
novabil=(a name)
nykøbing=(a name)
næsbyholmvej=(a name)
nørre-nebel=(a name)
nørregade=(a name)
octavia=(a name)
olfert=(a name)
oliver=(a name)
olivia=(a name)
omme=(a name)
opel=(a name)
operation=(a name)
oscar=(a name)
pakistan=(a name)
palæstina=(a name)
peddersen=(a name)
people=(a name)
peugeot=(a name)
pf=(a name)
philip=(a name)
picasso=(a name)
pius=(a name)
plane=(a name)
politkovskaja=(a name)
polo=(a name)
press=(a name)
pride=(a name)
publius=(a name)
pårup=(a name)
pølser=(a name)
queens=(a name)
ragnhild=(a name)
ragnhilds=(a name)
ravnholt=(a name)
reventlow=(a name)
ribe=(a name)
ringhof=(a name)
ringkøbing=(a name)
risskov=(a name)
roland=(a name)
rold=(a name)
romeo=(a name)
rosa=(a name)
rosenkilde=(a name)
roskilde=(a name)
roskildev=(a name)
rune=(a name)
rusland=(a name)
ryds=(a name)
rådhusklatreren=(a name)
rømer=(a name)
rørbæk=(a name)
sa=(a name)
saab=(a name)
sambiria=(a name)
samleren=(a name)
samosvej=(a name)
sande=(a name)
sander=(a name)
sankt=(a name)
saras=(a name)
schimmelmanns=(a name)
sdr=(a name)
sebastian=(a name)
sherlock=(a name)
silas=(a name)
silje=(a name)
silkeborg=(a name)
simmel=(a name)
simon=(a name)
sjælland=(a name)
skarrild=(a name)
skive=(a name)
skjaldedatter=(a name)
skoda=(a name)
skumtrøffel=(a name)
sky=(a name)
skødt=(a name)
slotsgade=(a name)
slotsherrensvej=(a name)
slotsholmsgade=(a name)
slx=(a name)
snakes=(a name)
snede=(a name)
solbjergvej=(a name)
sophie=(a name)
spanien=(a name)
sportnyt=(a name)
sprænghest=(a name)
sr=(a name)
statistik=(a name)
steens=(a name)
stenlandsvej=(a name)
stores=(a name)
stubkær=(a name)
sun=(a name)
sundbyerne=(a name)
sunds=(a name)
suzuki=(a name)
svendborg=(a name)
sw=(a name)
sønder=(a name)
sønderho=(a name)
søndermarken=(a name)
sørensens=(a name)
sørine=(a name)
taasingegade=(a name)
taxa=(a name)
tears=(a name)
thea=(a name)
thisted=(a name)
thomsen=(a name)
thorlund=(a name)
thyregod=(a name)
tiberius=(a name)
tilde=(a name)
tobias=(a name)
toftegårdsskolen=(a name)
tour=(a name)
toyota=(a name)
trattoria=(a name)
tristan=(a name)
ts=(a name)
ttv=(a name)
tulstrup=(a name)
tx=(a name)
tøjhusgade=(a name)
tøjhusgades=(a name)
tørring=(a name)
uhre=(a name)
undercover=(a name)
urt=(a name)
valby=(a name)
valdemar=(a name)
vesselsgade=(a name)
vesterbro=(a name)
vibeke=(a name)
viborggade=(a name)
viby=(a name)
victoria=(a name)
villads=(a name)
villestoftehaven=(a name)
vm=(a name)
vm-studiet=(a name)
volvo=(a name)
vtr=(a name)
vts=(a name)
vw=(a name)
william=(a name)
willumsvej=(a name)
worm=(a name)
x-men=(a name)
xsara=(a name)
xt=(a name)
yaris=(a name)
york=(a name)
zaren=(a name)
zarens=(a name)
zulu=(a name)
å=(a name)
århus=(a name)
ætnavej=(a name)
øgendahl=(a name)
østerbro=(a name)
autocaravans=motorhomes
total=total
knuds=(part of a street name: Skt. Knuds Stræde)
fifa-turnering=FIFA tournament
frost=(a name)
`;
